### ISSUE TITLE
Typechecker can't find an implementation when implicit instance used multiple times

### ISSUE THREAD

**Issue by youngmysteriouslight** [idris-lang/Idris2#1080]
### Steps to Reproduce
```haskell
data Ap : Type -> Type where
  mkAp : Ap a

QType : {0 a : Type} -> {auto ap : Ap a} -> Type
QType = Int

record Z (0 a : Type) where
  constructor mkZ

mkZWithConstraints : {auto ap : Ap a} -> Z a
mkZWithConstraints = mkZ

data Consumer : {0 a : Type} -> {auto ap : Ap a} -> (p : Z a) -> b -> Type where
  Consume : {0 a : Type} -> {auto ap : Ap a} -> {p : Z a} -> Consumer p b
```

Consider two examples: implicit
```haskell
Problem : {auto ap : Ap a} -> Consumer mkZWithConstraints QType
Problem = Consume
```
and explicit
```haskell
Problem : {auto ap : Ap a} -> Consumer (mkZWithConstraints {ap}) (QType {ap})
Problem = Consume
```

Use 5eafe11 version.

### Expected Behavior

They should 1) be equivalent and 2) type check fine.

### Observed Behavior

The first one produces
```
Error: While processing type of Problem. Can't find an implementation for Ap ?a.

ex.idr:16:19--16:52
 12 | 
 13 | data Consumer : {0 a : Type} -> {auto ap : Ap a} -> (p : Z a) -> b -> Type where
 14 |   Consume : {0 a : Type} -> {auto ap : Ap a} -> {p : Z a} -> Consumer p b
 15 | 
 16 | Problem : Ap a => Consumer mkZWithConstraints QType
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The second one is fine.

**Comment by gallais** [comment]
> Can't find an implementation for Ap ?a.

The problem here is that the problem is under-constrained: there is no indication
that `Consumer` should use the `a` that happens to be bound earlier in the telescope.
This should be clearer if you imagine that you have an `Ap Nat` in scope: why should
`Consumer` pick its implicit type to be `a` rather than `Nat`?
A partial fix is to make `Consumer`'s `a` argument explicit and insisting in `Problem`
that you are building a `Consumer a mkZWithConstraints QType`.

You then have the issue that `QType` and the slot it fits in are similarly polymorphic
enough that there is no reason to pick that one `a`. Making `QType`'s `a` explicit
solves that second issue.

You are finally faced with the fact that, because it is not applied and starts with
a lowercase, idris2 assumes that `mkZWithConstraints` is a variable it should implicitly
generalise over. By renaming `mk(...)` to `Mk(...)` you finally reach a point where
the file is accepted:

```idris
data Ap : Type -> Type where
  mkAp : Ap a
 
QType : (0 a : Type) -> {auto ap : Ap a} -> Type
QType a = Int
 
record Z (0 a : Type) where
  constructor mkZ
 
MkZWithConstraints : {auto ap : Ap a} -> Z a
MkZWithConstraints = mkZ
 
data Consumer : (0 a : Type) -> {auto ap : Ap a} -> (p : Z a) -> b -> Type where
  Consume : {0 a : Type} -> {auto ap : Ap a} -> {p : Z a} -> Consumer a p b
 
Problem : {auto ap : Ap a} -> Consumer a MkZWithConstraints (QType a)
Problem = Consume
```
