### ISSUE TITLE
INTERNAL ERROR $f is not a function appliation

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris2#110]
Idris2 throws an internal error as it treats a pattern variable as a function due to the pattern variable being named the same as the function in which the pattern is defined..

# Steps to Reproduce

```idris
module Trial

data Tup : (a,b : Type) -> Type where
  MkTup : (1 f : a) -> (1 s : b) -> Tup a b

f : Tup a b -> a
f (MkTup f s) = f
```

# Expected Behavior

An error that notices the duplicate name.

# Observed Behavior

The compiler throws an internal error.

```sh
Trial> :r
1/1: Building Trial (Trial.idr)
INTERNAL ERROR: $f is not a function application
Error(s) building file Trial.idr
```

Of note the error also appears with the following example:

```idris
f : Tup a b -> a
f (MkTup f s) = ?rhs
```

**Comment by edwinb** [comment]
This is an interesting message! It happens because you have a pattern variable that has the same name as the function you're defining, and it's got confused because it's seen 'f', noted that it's a pattern variable, and decided that *all* the fs on the lhs are therefore pattern variables, which is clearly not true.

I wonder what it *should* do in this situation though... should it be a more helpfully reported error? Or should the f pattern variable shadow the function name? My inclination is that it should be an error, because it's probably not what you intended.

**Comment by jfdm** [comment]
This should report the duplication as an error.

My programmer intuition tells me that if both the function name and pattern variables are both available on the rhs and available in the same scopes then they should be uniquely named. I am aware of shadowing but I think capturing programmer intent is better for this case.
