### ISSUE TITLE
Pattern matching on integers literals always return first case

### ISSUE THREAD

**Issue by ShinKage** [idris-lang/Idris2#112]
Pattern matching on integers literals (decimal, hexadecimal or octal) always returns the first case. This happens by directly matching function arguments and case expressions. If-then-else expressions work correctly.

This bug is present both in version 0.2.0 and 0.1.0 (before self-hosting).

# Steps to Reproduce
```idris
module Test

test1 : Int -> Int
test1 0x100 = 42
test1 0o100 = 43
test1 _         = 0

test2 : Int -> Int
test2 256 = 42
test2 64   = 43
test2 _      = 0

test3 : Int -> Int
test3 x = case x of
  0x100 => 42
  0o100 => 43
  _          => 0
```

# Expected Behavior
```
1/1: Building Test (Test.idr)
Test> test1 0
0
Test> test1 64
43
Test> test1 0x100
42
Test> test2 0
0
Test> test2 64
43
Test> test2 0o100
43
Test> test3 0
0
Test> test3 64
43
```

# Observed Behavior
```
1/1: Building Test (Test.idr)
Test> test1 0
42
Test> test1 64
42
Test> test1 0x100
42
Test> test2 0
42
Test> test2 64
42
Test> test2 0o100
42
Test> test3 0
42
Test> test3 64
42
```

**Comment by edwinb** [comment]
This turns out to be because in your first example, the definition checks as:

    test1 (fromInteger 256) = 42
    test1 64 = 43
    test1 _ = 0

...then the pattern match compiler decides it can't handle the `fromInteger` and treats it as a catch all case. Naturally, this shouldn't happen. It's because of a hack in the elaborator that shouldn't be there. I'd better fix this one quickly...
