### ISSUE TITLE
Test runner fails to compile when using a let instead of the expression

### ISSUE THREAD

**Issue by melted** [idris-lang/Idris2#116]
Using a let instead of the expression itself makes the test runner `tests/Main.idr` fail in type checking.

# Steps to Reproduce

Insert `result` instead of `normalize out == normalize exp` on  https://github.com/idris-lang/Idris2/blob/61ec7757ed485d55058a3991d8072f4f1db8a310/tests/Main.idr#L221 in the test runner.

# Expected Behavior

No change in behavior

# Observed Behavior

It fails to compile with 
```
Main.idr:222:26--223:21:While processing right hand side of runTest at Main.idr:166:1--231:1:
While processing right hand side of runTest,runTest' at Main.idr:206:9--231:1:
Can't solve constraint between:
        ()
and
        ?a [locals in scope: testPath, opts, {_:1513}, {_:1522}, out, {_cn:1}, exp]
```

**Comment by edwinb** [comment]
Here's a small program that has the same problem:

    f : Nat -> IO ()
    f x = do case x of
                Z => putStrLn "zero"
                S k => putStrLn "nonzero"
             putStrLn "Done"

(The rest of this is mostly rubberducking, but also by way of explanation...)

The error here comes from trying to infer a type for the `case` block. Since it doesn't know the type in advance, it invents a metavariable in the scope of the local context, so that's `?a x`. Checking the case branches leads to the following unification problems:

    ?a Z =?= ()
    ?a (S k) =?= ()

So, because `case` is dependent, the `x` gets substituted into the unknown type, and neither of the above problems can be solved by pattern unification, because we can only solve metavariables applied to a spine of unique variables.

The only plausible solution I can think of right now, which is really a hack, is to say that a `case` will be considered non-dependent if the type can't be inferred. I don't like this. In general, `case` does have to be dependent to do a lot of interesting things.

But, this sort of program really ought to type check! I will dig deeper into the unification literature...

**Comment by gallais** [comment]
We could have `case_return_of_` for the dependent one and `case_of_` for the
non dependent one. Users can write `case e return _ of alts` if they believe
Idris should be able to figure out the predicate corresponding to the return
type.

**Comment by edwinb** [comment]
Hmm, yes, I think the most common case is going to be non-dependent - at least for me, most uses of `case` are destructuring lets or binds, and if I have a dependent case I really mean it. So that seems like it could be a neat solution if nothing else is plausible.

**Comment by edwinb** [comment]
Actually if it defaults to non-dependent, that might also resolve all of the problems type checking `if` when it's non-dependent...

**Comment by ziman** [comment]
Then the dependent case can be magic and the nondependent one does not have to be.

**Comment by ziman** [comment]
And this may be a bit overkill but for full manual magic, we could optionally name the scrutinee like in Coq.
```idris
f : (x : Int) -> Either (even x = True) (even y = False)
f x = case b = even x `return` Either (b = True) (b = False) of
  True => Left Refl
  False => Right Refl
```
So Idris does not have to do this normalisation + rewriting dance.

I put `return` in backticks only so that it's highlighted but who knows what the real syntax should be. `->` and `=>` come to mind, too.

**Comment by edwinb** [comment]
I should perhaps add that the `TTImp` representation of `case` already allows for giving the return type explicitly. Because it doesn't assume that it's being given Idris specifically :). The Idris syntax itself doesn't allow giving this, however.

**Comment by gallais** [comment]
I am not sure I understand how we can give the return type using `the`. We can
give the instantiated return type for each one of the branches but that still does
not mean that Idris should be able to figure out the corresponding predicate,
does it?

**Comment by ziman** [comment]
My understanding is that you give the type for the whole `case` expression: `the T $ case ... of ...`. But the absence of `the` won't make `case` non-dependent and its presence won't make it magic, I guess.

I just find it strange that I have to write:
```
f : Nat -> IO ()
f x = do
  putStrLn "Starting"
  the (IO ()) $ case x of
    Z => putStrLn "zero"
    S k => putStrLn "nonzero"
  putStrLn "Done"
```
This does not look like a complicated situation that would require explicit annotations to me. All RHSes have very clearly inferrable type, the type is the same for each RHS, and the `do` block also requires `IO ()` to typecheck. And I'm also bugged by the extra parentheses around `IO ()`. :)

Could `do` propagate the type constraint? Or, alternatively, if the types of all RHSes unify, could that be the return type?

**Comment by edwinb** [comment]
I've been thinking about this on and off all weekend, and I now think that instead of mucking about in all kinds of ways, the Idris 1 solution is actually fine. Everthing else is needlessly complicated. This is only going to happen in free-standing case blocks inside 'do' where the result is discarded, and clearly you mean that to be (). If you didn't, you'd have said so.

It's not really about whether the case is dependent or not. The metavariable doesn't arise from the case block itself.

While I'm at it, I think I'll make `if` non-dependent. If you're using a Bool, it serves you right ;).
