### ISSUE TITLE
TypeSerach in REPL doesn't accept non-Pi type 

### ISSUE THREAD

**Issue by andylokandy** [idris-lang/Idris2#1193]
TypeSerach in REPL doesn't accept non-Pi type 

# Steps to Reproduce

```
> idris2
Main> :s Nat
Could not parse input as a type signature.
```

# Expected Behavior

`:s Nat` shows all constant function that returns `Nat`.

**Comment by gallais** [comment]
This is explicitly set in the `Idris.REPL` file: the type is checked to
be `Pi`-headed. I suspect this was put in place because with the current
implementation you get a lot of garbage when you look for a single concrete
type.

The trick is to filter out all the candidates whose type is `Erased`.
Patch incoming.
