### ISSUE TITLE
Module name starting with lowercase letter doesn't work

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#1224]
This is probably similar to #710

# Steps to Reproduce

Create file ggg.idr
```haskell
module ggg

export
yyy : Int
yyy = 0
```
Create file t.idr
```haskell
import ggg

t : Int
t = yyy
```
this works.
But
```haskell
import ggg

t : Int
t = ggg.yyy
```
fails. Changing the module name to Ggg fixes the problem.

# Expected Behavior

When creating or importing a module name starting with lowercase letter compilation should fail  an error message "Expected a capitalised identifier"

This requirement should be probably also described in:
https://github.com/idris-lang/Idris2/blob/master/docs/source/tutorial/modules.rst

**Comment by buzden** [comment]
This is the expected behaviour and this was changed two days ago in #1207. This definitely should be documented but is not yet.

**Comment by gallais** [comment]
Yeah, can you please stop filing the same issue over and over again?

**Comment by MilanKral** [comment]
sorry, my mistake. The issue should be now with module names not with namespace.
I already checked that namespaces names are fixed now.

**Comment by MilanKral** [comment]
As a side note, do postfix projection operator work only on names starting with lowercase?
```haskell
record Point where
  constructor MkPoint
  x : Int
  y : Int

G : Point
G = MkPoint 10 20

pp : Int
pp = G.x
```
fails.

But
```haskell
record Point where
  constructor MkPoint
  x : Int
  y : Int

G : Point
G = MkPoint 10 20

pp : Int
pp = G  .x
```
works

**Comment by gallais** [comment]
> sorry, my mistake. The issue should be now with module names not with namespace.

My bad. Thanks for the report! Working on it.

> As a side note, do postfix projection operators work only on names starting with lowercase?

Yeah that is inherently ambiguous. I guess we should force postfix projections to
be used with a space before them to lift all ambiguities. Thoughts @ziman?

**Comment by buzden** [comment]
> Yeah that is inherently ambiguous. I guess we should force postfix projections to
> be used with a space before them to lift all ambiguities.

Oh, no :-(

Well, I personally have used postfix projections tens times and only for lowercase identifiers while being loving syntactic look of it. Probably I'm wrong, but if a useful feature of spaceless projection would become a bit worse because of rare use-case (when using a projection with an upper-case identifier), maybe it's not worth doing. I mean, a space before the projection works with any case of an identifier. Why not mark spacy variant as the main variant in the documentation but still keep spaceless variant for lower-case identifiers?

**Comment by gallais** [comment]
I think consistency of the design and lack of ambiguities is more important
than cosmetic preferences.

**Comment by andrevidela** [comment]
Requiring a space before the postfix projection defeats the purpose of the feature: To ease the learning curve for people coming from languages which use the same postfix projection (aka, most of the programming languages out there, javascript, scala, rust, swift, Java, lua, C, C++)

The problem in general is that we cannot do this:

```
module Main

record R where
  constructor MkR
  field : Nat

MyRec : R
MyRec = MkR 3

main : IO ()
main = printLn (Main.MyRec.field)
```

But we can do this:

```
myRec : R
myRec = MkR 3

main : IO ()
main = printLn (Main.myRec.field)
```
This suggests to me that the problem is a lot less severe than one might think since the main use for capitalised identifiers is to use them in type signatures:

```
myRec1 : R
myRec1 = MkR 3

mkRec2 : R
myRec2 = MkR 3

prf : myRec1.field = myRec2.field
```
does not work but:

```
myRec1 : R
myRec1 = MkR 3

mkRec2 : R
myRec2 = MkR 3

prf : Main.myRec1.field = Main.myRec2.field
```

_does_ work. Having the rule that field projections do not work on capitalised instances of a record seems fine to me but there probably should be a warning about this. What do you think?
