### ISSUE TITLE
False negative in coverage checker when using `with`

### ISSUE THREAD

**Issue by claymager** [idris-lang/Idris2#1257]
When checking the following code:

```idris
covering
test : Maybe Int -> Int
test x with (x)
  test Nothing | Nothing = 0
  test (Just x) | with_pat = x
```

Idris falsely claims that the `with` block is not covering, because it thinks `Nothing | Just _` is a valid case.

This is independent of whether we're more explicit on the declared- or with-arguments.

**Comment by ShinKage** [comment]
AFAIU it's due to the how the with block is elaborated. The original code should be roughly elaborated to:
```idris
testWithBlock : (x : Maybe Int) -> (x : Maybe Int) -> Int
testWithBlock Nothing Nothing = 0
testWithBlock (Just x) with_pat = x

test : Maybe Int -> Int
test x = testWithBlock x x
```

So, as you can see, there is not obvious way of telling that the elaborated function is covering because the two argument do not unify.

To solve the issue you have two paths:
1. Use the `Syntax.WithProof` module like this `test x with (@@ x)`, so that you can pattern match on a dependent pair with a proof as second argument, and matching on that proof is convincing enough for the coverage checker.
2. Use the newly introduced `proof` extension to `with`, `test x with (x) proof eq`. This should bring in scope a `eq` that is the same proof of the previous solution and you can use `absurd` to provide the correct values for the impossible cases. However I think is not possible, currently, to match directly on the proof.

**Comment by claymager** [comment]
Got it. When `IWithApp` gets implemented, `x = test Nothing | (Just 7)` will be valid Idris, right?
