### ISSUE TITLE
Why are `sum` and `product` not tail recursive?

### ISSUE THREAD

**Issue by jinwoo** [idris-lang/Idris2#132]
Today I noticed that `sum` and `product` are defined with `foldr` rather than `foldl`: https://github.com/idris-lang/Idris2/blob/master/libs/prelude/Prelude.idr#L626-L634

It makes sense with Haskell because it's lazy. But Idris is an eager language and would it make more sense to make them tail recursive so that they don't stack overflow when given a large list of numbers? Or am I missing something?

**Comment by ziman** [comment]
The distinction between `foldr` and `foldl` in these functions matters because the compiler can see that `sum (x :: xs) = x + sum xs`. With `foldr`, this is a definitional equality, which is convenient for reasoning.

Besides, since `sum` and `product` are `public export`, this changes the interface of the module, and is potentially a breaking change.

So, to me, it makes sense to me that someone would intentionally make them `public export` and right folds: they constitute a specification for sums and products.

What about adding separate left fold versions instead? Or you could even make them `export` to say "you should not care how this is implemented" and perhaps supply some lemmas like `forall xs. sum' xs = sum xs` etc.

**Comment by jinwoo** [comment]
I was wondering about `public export` too. What you said about definitional equality makes sense if `public export` was actually intentional.

But I would assume that `sum` and `product` would be used much more often for term-level code than for type-level one. In that case, would it be better to make `sum` and `product` tail recursive and to create variants (say `sum'` and `product'`) that use `foldr` and can be used for definitional equality? `sum` and `product` would have then just `export` while `sum'` and `product'` would have `public export` because the fact that they use `foldr` should be part of the interface.

**Comment by jinwoo** [comment]
Updated https://github.com/idris-lang/Idris2/pull/142 so that `sum'` and `product'` are provided separately, leaving `sum` and `product` as they are.

**Comment by ohad** [comment]
What I've done before, is supply an additional module (in `contrib`, `Data.Nat.TailRec.idr`) that `export`s the tail recursive versions, and exports proofs that they are extensionally equivalent to their non-tail-recursive versions.

The idea is that if you really care about the tail-recursion (due to performance), you could use those versions and at the cost of a few rewrites you could present them to the type-checker as if they were normalisation-friendly.

I haven't _really_ used this in practice though, so perhaps it's too klunky.
