### ISSUE TITLE
Cmd `:t` does not print infix function applications enclosed in grave accents 

### ISSUE THREAD

**Issue by alissa-tung** [idris-lang/Idris2#1328]
# Steps to Reproduce
```idris
module Main

data InSet : (a, b : _) -> Type where
infix 4 `InSet`

prop : x `InSet` a
prop = ?undef
```

# Expected Behavior
```idris
Main> :t undef 
 0 x : _
 0 a : _
------------------------------
undef : x `InSet` a
```

# Observed Behavior
```idris
Main> :t undef 
 0 x : _
 0 a : _
------------------------------
undef : x InSet a
```

**Comment by gallais** [comment]
You can see that here we simply show the `OpStr` (a name):
https://github.com/idris-lang/Idris2/blob/9a445f57e69ba286a1148a057cd450daab25e0f2/src/Idris/Syntax.idr#L599

A fix would be to look at the name to decide whether it is an operator
or not and change the printing strategy depending on that.

**Comment by ohad** [comment]
I don't think we should display 
```idris
x `InSet` a
```
as `x InSet a`.

Rationale: copy-pasting the printed code into the program should result in valid code.
Since `x InSet a` is not valid code, I prefer the current behaviour over the expected behaviour.

I think we currently violate this principle in other place, for instance with how we print brackets, but still it would be good to fix those other places.

**Comment by ohad** [comment]
I think the rationale should be: copy-pasting printed code into the program should result in valid code.

**Comment by gallais** [comment]
Mumble mumble Pollack consistency
