### ISSUE TITLE
[ Nix, Racket, Termux, Install ] Idris2 cannot bootstrap properly on Arch Termux with Nix via Racket.

### ISSUE THREAD

**Issue by gh-name** [idris-lang/Idris2#1410]
### Possible Resolution: https://github.com/idris-lang/Idris2/issues/1410#issuecomment-841738378
https://github.com/gh-name/Idris2
Is there anyone willing to add building options for the Racket backend, namely, let users set specify which Racket variant they are willing to use, and than update the bootstrap compiler code? In addition, a debug option `--3m --gui` is useful.
IMO a case expression in `bootstrap-stage1-racket.sh`, new enviroment variables in `src/Idris/Env.idr`'s envs, and cases in `findRacoExe`?
My x86_64-linux device can not use `--3m` and my aarch64-linux device can not use `--cs` so there is no way to do `make` and `make install` but only `make bootstrap-racket`.

The log is:
```sh
Bootstrapping IDRIS2_VERSION=0.3.0                      ffi-lib: couldn't open "libidris2_support.so" (dlopen failed: library "libc.so.6" not found: needed by /root/.mpkgs/lang/Idris2/build/exec/idris2_app/libidris2_support.so in namespace (default))
  context...:
   /data/data/com.termux/files/usr/share/racket/collects/ffi/unsafe.rkt:130:0: get-ffi-lib9
make[2]: *** [Makefile:2: all] Error 1
make[2]: Leaving directory '/root/.mpkgs/lang/Idris2/libs/prelude'
make[1]: *** [Makefile:71: prelude] Error 2
make[1]: Leaving directory '/root/.mpkgs/lang/Idris2'
make: *** [Makefile:199: bootstrap-racket] Error 2
make bootstrap-racket  268.38s user 4.95s system 91% cpu 4:57.52 total
```
If do `ln -sf /usr/lib/libc.so.6 /usr/lib64/libc.so.6` leads to a different type of error:
```sh
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/.mpkgs/lang/Idris2/support/chez'
cp support/c/libidris2_support.so bootstrap/idris2_app
sed 's|__PREFIX__|/root/.mpkgs/lang/Idris2/bootstrap|g' \
        bootstrap/idris2_app/idris2.rkt \
        > bootstrap/idris2_app/idris2-boot.rkt
/bin/sh ./bootstrap-stage1-racket.sh
Bootstrapping IDRIS2_VERSION=0.3.0
Building idris2-boot from idris2-boot.rkt
SIGSEGV MAPERR si_code 1 fault on addr 0x759f901623
./bootstrap-stage1-racket.sh: line 14:  3673 Aborted                 raco exe idris2_app/idris2-boot.rkt
make: *** [Makefile:198: bootstrap-racket] Error 134
make bootstrap-racket  224.38s user 4.18s system 93% cpu 4:05.21 total
```

**Comment by gallais** [comment]
Did you manage to fix your problem? What was the solution?

**Comment by dotpat** [comment]
> Did you manage to fix your problem? What was the solution?

I changed Racket to Nix unstable channel's Racket 8.0 [cs], the problem now turn into
```
can't find Racket executable for variant cs
```
.

I had seen people use Idris2 on their mobiles only once, so I am wonder is this a fair usage of the program. That's quiet annoying and I decided to give up, so many different type of errors are yet not informative though. The package on Nix requires Chez so it doesn't work yet, maybe they need a modify… but I had managed to run Agda and Haskell、GHC、GHCup、HLS……

**Comment by dotpat** [comment]
> Did you manage to fix your problem? What was the solution?

Yes, it's due to a nix and Racket bug，see https://github.com/NixOS/nixpkgs/issues/114993

**Comment by dotpat** [comment]
I finally managed to bootstrap and install Idris 2 on a mobile phone, and here are some logs:
- It's not recommend to use the Racket in Termux directly, some told me that they had done bootstrap with Idris v0.2.1, but on my device that doesn't work yet and lead to mysterious error*s*.
- If you are using minimal Racket without dependencies installed, the error messages a not informative at all. In conclusion, if `raco exe` is missing, do `raco pkg install --auto compiler-lib`, if `rnrs` no found, do the same for `r6rs-lib`. Anyway, use full version Racket can be easier.
- Due to some historical reasons, Nix and Racket can not interactive each other well. So just modify `bootstrap-stage1-racket.sh` with `raco exe` \to `raco exe --3m --gui`. Yes, that's tedious…

ping @gallais | I think the above in some ways… can be helpful with the suitable definitions. Please check if something is misleading.

Ref: [https://github.com/NixOS/nixpkgs/issues/114993, https://github.com/NixOS/nixpkgs/issues/11698]
![Screenshot_20210516-071822](https://user-images.githubusercontent.com/80032304/118380774-020f6b00-b617-11eb-88a2-07e1675c7a29.png)

**Comment by dotpat** [comment]
Same there: no idris2.so
https://github.com/idris-lang/Idris2/issues/1244#issue-842846759

**Comment by dotpat** [comment]
> Same there: no idris2.so
> [#1244 (comment)](https://github.com/idris-lang/Idris2/issues/1244#issue-842846759)
> 
> ```shell
> /home/nonroot/mbuild/Idris2/build/exec/idris2_app/idris2.so: No such file or directory
> make[1]: *** [Makefile:2: all] Error 127
> make[1]: Leaving directory '/home/nonroot/mbuild/Idris2/libs/prelude'
> make: *** [Makefile:71: prelude] Error 2
> IDRIS2_BOOT=/home/nonroot/.idris2/bin/idris2 make  22.45s user 5.63s system 79% cpu 35.271 total
> ```

That turns out to be the problem of `IDRIS2_GC` wasn't set, if set to `racket` then `can't find Racket executable for variant cs`.
So can we just add one more environment variable in the `envs : List EnvDesc` for Nix + Racket users, then modify `findRacoExe` in two clauses so that can perform `--3m --gui`, and update the bootstrap code? Afterwards, it can do a bootstrap job but not self-hosting because of `can't find Racket executable for variant cs`.

**Comment by melted** [comment]
The CS variant is the default version of Racket since 8.0, so maybe there is some outdated reference somewhere?

**Comment by dotpat** [comment]
> The CS variant is the default version of Racket since 8.0, so maybe there is some outdated reference somewhere?

I think that cause the problem and we could specify the options at least for arm devices do not have chez at home…

**Comment by dotpat** [comment]
I am trying to make a prototype in order to verify whether this can fix. Currently looking for a method to update the bootstrap Racket source code and the key to join # idris at Functional Programming Slack. Are there any instructions available?

**Comment by gh-name** [comment]
Is there anyone willing to add building options for the Racket backend, namely, let users set specify which Racket variant they are willing to use, and than update the bootstrap compiler code? In addition, a debug option `--3m --gui` is useful.
IMO a case expression in `bootstrap-stage1-racket.sh`, new enviroment variables in `src/Idris/Env.idr`'s envs, and cases in `findRacoExe`?
My x86_64-linux device can not use `--3m` and my aarch64-linux device can not use `--cs` so there is no way to do `make` and `make install` but only `make bootstrap-racket`.

**Comment by gh-name** [comment]
Turns out that I just need to build Racket v8.1 from source.

**Comment by benhormann** [comment]
Racket's variant of Chez supports ARM. It's a good option, if you have enough RAM.

Build on device: [racket/src/ChezScheme/BUILDING](https://github.com/racket/racket/blob/master/racket/src/ChezScheme/BUILDING). Download a [source tarball](https://download.racket-lang.org/releases/), then:
```
./configure --pb
make tarm64le.bootquick
./configure --threads --disable-x11 LIBS=-liconv --installprefix=$HOME/.chez
make && make install
```
It snags without `LIBS=-liconv`, probably just a Termux prefix related issue.
