### ISSUE TITLE
Irrelevant arguments in runtime relevant positions inside types inside runtime-relevant types should be OK

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1436]
# Steps to Reproduce
```idris
data Foo : (n : Nat) -> Type where

bar : Type
bar = (0 n : Nat) -> (bar : Foo n) -> Nat
```

# Expected Behavior
Type-check fine.
Rationale (due to @CodingCellist ): moving the definition of bar to the right of a colon would be fine, so we should be able to create a runtime representation for it.

# Observed Behavior
```
 While processing right hand side of bar. n is not accessible in this context.
```
```idris    
      1 | data Foo : (n : Nat) -> Type where
      2 | 
      3 | bar : Type
      4 | bar = (0 n : Nat) -> (bar : Foo n) -> Nat
                   ^
```

**Comment by CodingCellist** [comment]
It seems, according to Edwin, that this might actually be expected behaviour. Quoting a reply from the Discord:

> 2021-05-19 [12:18] edwinb: Foo uses n, and matching on the expansion of bar may require knowing Foo n in full. You say bar is usable at run time, so you have to know Foo n in full at run time. The usual rules for quantities apply, there's nothing special about types. The only weird thing here is the possibility of matching on ->

IIUC, since `bar` is not 0-linear, its contents can't be either, since you'd otherwise need something which isn't available at runtime, to evaluate/expand `bar`.

I think where my previous reasoning falls short is that since `bar` is recursive _and_ available at runtime, either all the arguments have to available at runtime or `bar` must also be 0-linear.

(I'm still getting the hang of this whole linearity thing, so please correct me if I misunderstood something ^^ )
