### ISSUE TITLE
Parameters to parameterised definitions in record fields aren't applied correctly

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1482]
# Steps to Reproduce
```idris
parameters (X : Nat)
  Foo : Type
  Foo = Nat

  -- This doesn't work
  record Bar where
    constructor MkBar
    Gnu : Foo 
  
  -- This works fine
  Baz : Foo -> Nat
  Baz x = x


-- This works fine
parameters (X : Nat)
  record Bar' where
    constructor MkBar'
    Gnu' : Foo X
    
```
# Expected Behavior
All definitions should type-check.

# Observed Behavior
`Bar` fails to type-check with:
```
     While processing type of .Gnu. When unifying Type and Nat -> Type.
     Mismatch between: Type and Nat -> Type.
     
     Rec.idr:8:11--8:14
      4 | 
      5 |   -- This doesn't work
      6 |   record Bar where
      7 |     constructor MkBar
      8 |     Gnu : Foo 
                    ^^^
```

**Comment by ohad** [comment]
# Workaround
Put the definition outside the parameters block and pass the arguments explicitly:
```idris
parameters (X : Nat)
  Foo : Type
  Foo = Nat

parameters (X : Nat)
  record Bar where
    constructor MkBar
    Gnu : Foo X
```

**Comment by gallais** [comment]
The problem is that we elaborate the record constructor & then use the
elaborated type to build the projections. But that elaborated type has
already been expanded to have all of the parameters applied!

It's a bit hard to fix. :/

**Comment by edwinb** [comment]
I've just been having a look at this - as @gallais says, we're using `unelab` to build the type of the getter, which we really shouldn't do because it's unaware of the environment it's built in. I can think of a hacky solution but I'll try to think of a non-hacky one before I do anything about it. Implementations of interfaces don't work in parameters blocks (or where clauses, which are basically the same thing) for a related reason so it's probably worth putting a bit of thought into doing it right.

**Comment by edwinb** [comment]
I don't know why I put words like "probably" in there. It's definitely worth doing right :).
