### ISSUE TITLE
Failure to unify in let clauses

### ISSUE THREAD

**Issue by danielwaterworth** [idris-lang/Idris2#1490]
# Steps to Reproduce
```idris
module Bug

x : Bool
x =
  let
    x = True && True
    prf = the (x = True && True) Refl
  in
    True
```

# Expected Behavior

I would expect this to type check.

# Observed Behavior

```
Error: While processing right hand side of x. When unifying True = True and x = True && Delay True.
Mismatch between: True and x.

Bug.idr:7:34--7:38
 3 | x : Bool
 4 | x =
 5 |   let
 6 |     x = True && True
 7 |     prf = the (x = True && True) Refl
                                      ^^^^
```

**Comment by ohad** [comment]
This is confusing, but intended behaviour (though I wish it wasn't!).

[From the documentation](https://idris2.readthedocs.io/en/latest/updates/updates.html?highlight=let#let-bindings):

> let bindings, i.e. expressions of the form let x = val in e have slightly different behaviour. Previously, you could rely on the computational behaviour of x in the scope of e, so type checking could take into account that x reduces to val. Unfortunately, this leads to complications with case and with clauses: if we want to preserve the computational behaviour, we would need to make significant changes to the way case and with are elaborated.
> 
> So, for simplicity and consistency (and, realistically, because I don’t have enough time to resolve the problem for case and with) the above expression let x = val in e is equivalent to (\x => e) val.
> 
> So, let now effectively generalises a complex subexpression. If you do need the computational behaviour of a definition, it is now possible using local function definitions instead - see Section Local function definitions below.

Concretely for this example, it means that you need to turn the let-binding of `x` into a local definition:
```idris
x : Bool
x =
  let
    x : Bool
    x = True && True
    prf := the (x = True && True) Refl
  in
    True
```

(The assignment `:=` in `prf` disambiguates parsing this line as a let-binding, otherwise the parser thinks it's a local-definition without a type-declaration, see #1485 .)

**Comment by danielwaterworth** [comment]
That makes sense. Thanks @ohad!
