### ISSUE TITLE
[PROPOSAL] Some syntax sugars

### ISSUE THREAD

**Issue by glyh** [idris-lang/Idris2#1513]
1. Allow pattern matching constants defined in global socpe:

```idris
data Fruit = Apple | Banana

apple : String
apple = "apple"

banana : String
banana = "banana"

whichFruit : String -> Fruit
whichFruit #apple = Apple
whichFruit #banana = Banana
```

Although this can be achieved by a group of if statements, it can become harder and harder to achieve when the structure grows. 

2. Avoid repeating function names: 

```idris
aVeryLongFunctionNameThatYouNeverWantToTypeOrSeeAgain : (a -> b) -> List a -> List b 
  f [] = []
  f (x :: xs) = f x :: recur f xs
```
Where "recur" is a keyword for recursion, which is not limited to tail call( like Clojure). 

Although most of the time the repeated function names are generated by Idris's type inference system, this adds some visual noises. 

3. Allow type information and definition to combine together: 

```idris
double : (List Int -> List Int) = map (\x -> x * 2) -- A function definition
banana : String = "banana" -- A constant definition
```

I think these can not only reduce your codebase, but also make it cleaner to read.

**Comment by michaelmesser** [comment]
The proposed syntax for suggestion 3 conflicts with an existing use of `=`.

**Comment by glyh** [comment]
@michaelmesser This sounds reasonable. Maybe we can just have the first 2. 

```idris
double : (List Int -> List Int) 
  = map (\x -> x * 2) -- A function definition
banana : String 
  = "banana" -- A constant definition
```

**Comment by gallais** [comment]
1. There's a more general concept: patter synonyms
3. You can write `x : Nat; x = 3`. Allowing `x : Nat = 3` would lead to ambiguities in `let`.

**Comment by glyh** [comment]
@gallais 
1. I'll go and see, thanks a lot. 

2. It's just a sugar to write if your function name is too long... 
parameter patterns "f []" and "f (x :: xs)" can be picked when: 
  a. There's a type declaration and the parameter patterns follows it in the next line with a indentation before it. 
  b. The last line is a definition (i.e. has the form of : "<Indent> <Parameter Patterns> <Literal => < rhs >") , and this line has the same structure (Same number of spaces are required)

3. Yeah I see that. But I think maybe from the beginning, the Refl type should not use "=" as part of it's Type information, this limit the grow of syntax.

**Comment by Josef-Vonasek** [comment]
I would prefer a keyword like `self` instead of `recur`.

**Comment by Josef-Vonasek** [comment]
I would also suggest another syntax for 1:
```haskell
data Fruit = Apple | Banana

strApple   = "apple"
strBanana = "banana"

whichFruit : String -> Fruit
whichFruit StrApple = Apple
whichFruit StrBanana = Banana
```

**Comment by Josef-Vonasek** [comment]
Finally, I also have an idea for syntax sugar number 4:
```
record { a := foo it (bar it) } == record { a $= \a -> foo a (bar a) }
```
And `$=` is removed from the language.

**Comment by glyh** [comment]
We can also have syntax sugar 2 for with blocks: 
```idris
describeListEnd : List Int -> String
  input with (listLast input)
    input | with_pattern  = ?describeListEnd_rhs
```
which is a function `describeListEnd`, with view listLast attach to it.

**Comment by edwinb** [comment]
What we really need here is pattern synonyms. One possible way to do that would be to say that a function is reducible on the LHS (and we already have this for `fromInteger`, `fromString` etc).

In general, I'm reluctant to add any more sugar without a really strong reason for it, since Idris is a big enough language without it and the sugar we have is already tricky to explain sometimes.

**Comment by Josef-Vonasek** [comment]
@edwinb So what do you think of (4): `record { a := foo it (bar it) }`  replacing  `record { a $= \a -> foo a (bar a) }`.

It does not add new syntax, it just replaces a syntax with a more readable variant.

**Comment by andrevidela** [comment]
I think we've reached the point in this project where any new syntax proposal must be substantiated with actual use-cases. It helps if the conversation had already been had in another setting so that we don't have to rehash the same arguments (what does Haskell or Agda do about it for example?). It also help if you already have a large codebase where the problem is recurring and plainly apparent, this way everyone can understand the problem, and everyone can imagine a solution for it.

@Josef-Vonasek is this a problem you've encountered a lot? maybe we can take a look and try to extract a pattern out of it. I'm not yet convinced that the implicit presence of an argument is a good thing:
 - will `it` work in every closure? what about function definitions?
 - How do you refer to the second argument?
 - Your own example is ambiguous since `it` is used multiple times: is it `foo it (bar it) = \x => foo x (bar x)` or `foo it (bar it) => \x, y => foo x (bar y)` or `foo it (bar it) = \x => foo x (\y => bar y)`?

Scala has the `_` syntax that approaches your solution but its rules do not permit your use-case: each use of `_` must be linear, that is so that `_ + _ ` = `\x => \y => x + y`. Swift has an argument short-hand syntax `$0` but then the (reverse) debrujin index is carried in the identifier of the shorthand, making unambiguous, which mean you could write `foo $0 (bar $1)` for` \x => \y => foo x (bar y)`

**Comment by glyh** [comment]
Allow patterns in matching to use twice, without a proof. 

For example:

```idris
equiv : Char -> Char -> Bool
equiv c c = True 
equiv _ _ = False
```

**Comment by Josef-Vonasek** [comment]
@andrevidela 

1. It's a syntax sugar that works only inside `:=`. The lambda binds to `:=`, not `(..)`.
2. That means there is always exactly one argument, nor any other ambiguity.
3. I will repeat it third time -.-. It means record `{ a $= \a -> foo a (bar a) }`. 

The keyword `it` is taken from Kotlin, where it means the same thing as `$0` in swift.

**Comment by andrevidela** [comment]
I apologise I didn't mean to make you repeat yourself, rather, highlight that the fact that, without additional restriction, the semantics are ambiguous. You've provided additional restrictions so it's a bit more clear what the feature should do, however I would like to attract your attention to the fact that record fields can have additional arguments (you nº2 point):

```
record Ops where
  constructor MkOps
  fn : Int -> Int -> Int
updateOp : Ops -> Ops
updateOp = record { fn $= \op, x, y => op (op x y) (op x y) }
```

Which in your example would become 

```
updateOp = record { fn := \x, y => it (it x y) (it x y) }
```

But at this point I'm not sure we've gained anything. It makes the syntax inconsistent: `it` doesn't mean `$0` anymore, or at least not the `$0` from swift because you can't use it inside nested closures. Which means you can't write this:

```swift
let notOk : (@escaping (Int, Int) -> Int) -> ((Int, Int) -> Int) =
    {x, y in $0(x, y) }
```

ps: `:=` is already used in let bindings so you'd have to come up with yet another symbol https://idris2.readthedocs.io/en/latest/tutorial/typesfuns.html#sect-let-bindings

**Comment by Josef-Vonasek** [comment]
> ps: := is already used in let bindings
Ah, I thought it's used in record updates. In that case it should be ` field = ... it ...` (same binding operator as setter).

I also wouldn't call the `fn` case a multi argument field. To be frank, I would even say that the abuse of currying there `\op, x, y => ..` is an anti pattern. 

Not sure about the last example, I don't want `it` to be a replacement for `$0`. It's purpose is to make updates look like setters. Instead of using some alien `$=` symbols.

**Comment by andrevidela** [comment]
`$=` might seem alien at first glance but it's meant to be the "setter" version of `$` which applies a function to its argument. Likewise, `$=` applies the function to the field selected. It might not be to your taste, but it's a consistent design choice in how to work with records and data.

The last example only illustrates the fact shorthands can't be nested in closures, which is problematic in Idris.

**Comment by glyh** [comment]
Also, I think there's a need for us to provide `default implementation` for some interface. 

For example, the ord interface: 

```idris
data CharSetRange = CRLessOrEq Char
                  | CRMoreOrEq Char
                  | CRRange Char Char

data Regex = Empty
           | Epsilon
           | Lit Char
           -- CharSet is decided with a group of predicates
           | CharSet (List CharSetRange)
           | Concat (List Regex)
           -- Closures
           | Kleen Regex
           -- Boolean algebras
           | And (List Regex)
           | Or (List Regex)
           | Not Regex
```

If I try to provide a order for this, which is required by the Brzozowski Derivative algorithm, I've got to write  ![time](http://www.sciweavers.org/tex2img.php?eq=%5COmega%20%28n%5E2%29%20&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0) cases.

However, there is a possibility to provide default orders for union types, let's take Regex for example: 
1. Epsilon < Lit < CharSet < Concat < Kleen < And < Or < Not, i.e. the relation depends on the order that constructors occurs. 
2. "Lit a < Lit b" is equivlent to "a < b"

This is almost what we want most of the time, and having these can really help you out from repeating yourself. 

For Eq interfaces, we can provide the default one as:
Try convert Refl to type (a = b), if success, then it's true, if not, it's false. 

To prevent unconciously use these default implementations, we can add these syntaxs : 

```idris
Ord Regex Default 
Eq Regex Default
```
Use Default to explicitly tell compiler to generate a order for this type.

**Comment by glyh** [comment]
@edwinb Will you accept pull requests for these?

**Comment by ShinKage** [comment]
@glyh I don't think we need to hardcode non-ubiquitous defaults into the compiler. You can easily and automatically derive such implementations at compile time with ElaboratorReflection. The question then is, should we add some ElabReflection utilities directly with the repository packages, or leave it to third-party packages?

**Comment by gallais** [comment]
> Will you accept pull requests for these?

We now have half a dozen different proposals all interleaved into this thread
none of which have been clearly described (both in terms of syntax & semantics)
as far as I am concerned.

As André said it's better to discuss & settle on a clear design backed by test
cases rather than jumping straight to PRs. Ideally we'd discuss only one idea
per issue.
