### ISSUE TITLE
Can't make directory.

### ISSUE THREAD

**Issue by Kesanov** [idris-lang/Idris2#1524]
test.ipkg:
```
package test

sourcedir = "src"
modules   = Main
```
src/Main.idr:
```
module Main
```
command:
```
>>> idris2  --install test.ipkg
Uncaught error: INTERNAL ERROR: Can't make directory test
```
OS: WSL

**Comment by gallais** [comment]
Does idris2 have the right to create the directory `~/.idris2/idris2-0.3.0/test`?

**Comment by Josef-Vonasek** [comment]
How can I check that?

**Comment by Josef-Vonasek** [comment]
If I do `sudo idris2 --instal test.ipkg` I get ` sudo: idris2: command not found`

**Comment by fabianhjr** [comment]
Hi @Josef-Vonasek, for clarification, did you install it from the packaged v0.3.0 version (`nix-env -iA nixpkgs.idris2`) or did you build from source and install the result? (`nix-build -E "with import <nixpkgs> {}; (callPackage ./. {})" && nix-env -i result/`)

I don't have Windows but could you do `tree ~/.idris2/ -L 2` to check that directory?

**Comment by fabianhjr** [comment]
Hey, could you try using this nix packages? https://github.com/claymager/idris2-pkgs

**Comment by Josef-Vonasek** [comment]
All I want to do is run a simple hello world package with no external dependencies. I don't see how packager manager helps that.

**Comment by fabianhjr** [comment]
@Josef-Vonasek, the issue is that nix copied everything to a non-mutable store (this is as designed) so you cannot copy more stuff over the nix install of Idris2.

You could try to move around it in a hacky way (Copying the Nix Idris2 install to ~/.idris2 a setting the env `IDRIS2_PREFIX`) however that would probably cause a bit more issues (since on an `nix-env -u` and a garbage collection the dependencies of the copied idris2 might get removed)

The other option would be to make it from source, this is what I do on NixOS and should work better for you too. Clone this repo, `nix-shell` and follow the bootstraping instructions here, use the normal `make install` which will install idris2 in your home dir and remember to add the idris2 bin to your PATH. (I use a symbolic link from `~/.local/bin` to `~/.idris2/bin/idris2` and have `~/.local/bin` in my PATH)

**Comment by claymager** [comment]
@Josef-Vonasek Does running `$ mkdir -p $(idris2 --libdir)` fix your issue?

There is a disagreement between nix and idris2:
 - idris2 expects either $IDRIS2_PREFIX or `~/idris2/idris2-0.3.0` to exist
 - nix refuses to make either one

#1300 would help, but the idris2 in nixpkgs is pinned to the last release, and there were a few packaging changes this spring that are not included yet.

**Comment by Josef-Vonasek** [comment]
>  Does running $ mkdir -p $(idris2 --libdir) fix your issue?
Nope.

**Comment by fabianhjr** [comment]
Hey @Josef-Vonasek, that is a read-only store where you cannot install more libraries over. Only nix commands can add to that store.

**Comment by claymager** [comment]
Oops. Forgot I had IDRIS2_PREFIX set, sorry. Add that to your shell env and it should work.

----

Order of precedence for libdir is
 - IDRIS2_PREFIX at runtime
 - if IDRIS2_PREFIX is set at buildtime
    - then that
    - else build location
 
Build location is immutable, so obviously out. The nix package chooses not to set IDRIS2_PREFIX, but setting a default is trivial and the approach I'm taking in `idris2-pkgs`.

We still need to make sure idris properly handles the libdir not existing.
