### ISSUE TITLE
typechecker isn't reporting covering error

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#1537]
```
module CoverBug

import Data.So

public export
data FastNat : Type where
  MkFastNat : (val : Integer) -> {auto 0 prf : So True} -> FastNat
  
prv1 : Integer -> (x : Integer ** So $ True)
prv1 x = 
  case choose True of
    Left prf => (x ** Oh)
    Right noprf => absurd noprf

fromInteger : Integer -> FastNat
fromInteger v = 
  let (v ** p) = prv1 $ v
  in MkFastNat v
    
doit : FastNat -> FastNat
doit 0 = 0
```
https://gist.github.com/redfish64/a097a400aab1114a71ff34235a0fe90f

doit should report a covering error, but does not.

**Comment by Z-snails** [comment]
This reminds me of #1196.
`doit` would be desugared/elaborated to
```haskell
doit : FastNat -> FastNat
doit (MkFastNat 1) = MkFastNat 1
```

**Comment by edwinb** [comment]
I had a quick look. `doit` is elaborating to:

    CoverBug> :printdef doit
    CoverBug.doit : FastNat -> FastNat
    doit (let MkDPair v p =
                case choose True of
                {Left prf => MkDPair x Oh;
                Right noprf => absurd noprf}
          in MkFastNat v) = let MkDPair v p =
                                  case choose True of
                                  {Left prf => MkDPair x Oh;
                                  Right noprf => absurd noprf}
                            in MkFastNat v

...which is beyond the coverage checker. In fact that `let` on the LHS is supposed to be evaluated in order to give the checker a chance, but currently it isn't.

If you write the definition as @Z-snails suggests, then it does detect the problem, which is reassuring, so I hope sorting out the LHS evaluation will fix this and related issues. The linked issue appears to be something else, though?

**Comment by edwinb** [comment]
Heh, interestingly, the way it compiles that pattern, it actually is covering, because it treats the LHS pattern as a 'catch all'. So it's covering, but only because it's compiled a function that isn't the one you wrote... anyway. there is a small fix for this coming shortly.
