### ISSUE TITLE
append function - linear name

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#1560]
# Steps to Reproduce

When compiling

```haskell
%default total

append : (1 _ : List a) -> (1 _ : List a) -> List a
append [] ys = ys
append (x :: xs) ys = x :: append xs ys
```

I get error:
```haskell

Error: While processing right hand side of append. Trying to use linear name ys in non-linear context.

c:5:38--5:40
 1 | %default total
 2 | 
 3 | append : (1 _ : List a) -> (1 _ : List a) -> List a
 4 | append [] ys = ys
 5 | append (x :: xs) ys = x :: append xs ys
                                          ^^
```

# Expected Behavior

The example is shown at
"Edwin Brady Tells Us What's New in Idris 2"
https://www.youtube.com/watch?v=nbClauMCeds

time 26:37

it should compile.

**Comment by buzden** [comment]
Unfortunately, for now this is an expected behaviour. It all depends on how `List` type is defined. E.g., this typechecks:

```idris
%default total                      
                    
%hide Prelude.List                                       
                                    
data List : Type -> Type where                           
  Nil  : List a                                      
  (::) : (1 _ : a) -> (1 _ : List a) -> List a                
                                                         
append : (1 _ : List a) -> (1 _ : List a) -> List a      
append [] ys = ys                            
append (x :: xs) ys = x :: append xs ys
```

In this `List` definition both arguments of `::` constructor are linear, thus the whole expression are in the linear context when calling it, thus `append xs ys` is in linear context, thus `ys` is in linear context. As soon as `::` constructor is not linear on its second argument, the whole expression `append xs ys` is not in linear context, thus `ys` is neither.

**Comment by gallais** [comment]
Following #879 the datatypes in the base libraries do not have linear constructors
anymore. For `append` to be linear you'll need define your own type of lists:

```idris
data LinearList : Type -> Type where
  Nil  : LinearList a
  (::) : (1 x : a) -> (1 xs : LinearList a) -> LinearList a
```
