### ISSUE TITLE
Can't solve constaint for equality on record fields

### ISSUE THREAD

**Issue by po-stulate** [idris-lang/Idris2#1675]
# Steps to Reproduce
```idris
record HasNat where
  constructor MkHasNat
  n : Nat

hasNat : HasNat
hasNat = MkHasNat Z

x : hasNat.n = Z
x = Refl
```
# Expected Behavior
I would expect this to type check?

# Observed Behavior
`While processing right hand side of x. Can't solve constraint between: 0 and hasNat .n.`

**Comment by edwinb** [comment]
This works:

      x : Main.hasNat.n = Z
      x = Refl

It's because it's treating `hasNat` as an unbound implicit, by the usual rules (see here: https://docs.idris-lang.org/en/latest/faq/faq.html#why-can-t-i-use-a-function-with-no-arguments-in-a-type - I should move the questions that are still relevant there to the Idris 2 FAQ!)

I reckon this rule shouldn't apply to record projections since it's clear what you mean here. But still, it parses as `.n hasNat` so the rules as implemented would just pick up `hasNat` as an unbound implicit.

**Comment by gallais** [comment]
Worth noting that in Idris2 0.4.0 you should get a warning like so:

```
Warning: We are about to implicitly bind the following lowercase names.
You may be unintentionally shadowing the associated global definitions:
  hasNat is shadowing Main.hasNat
```
