### ISSUE TITLE
IDE type-at-point behaves incorrectly for suffix operators

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1744]
# Steps to Reproduce
```idris
(.suffix) : Nat -> Nat
0.suffix = 0
(S k).suffix = k

foo1 : Nat -> Nat
foo1 n = n.suffix

foo2 : Nat -> Nat
foo2 n = n .suffix

foo3 : Nat -> Nat
foo3 n = (.suffix) n
```
Place the cursor on the `.suffix`  calls in `fail`i and ask the IDE protocol for type-at-point.

# Expected Behavior
All 3 should respond with `(.suffix) : Nat -> Nat`.

# Observed Behavior
All 3 fail with:
```
Undefined name suffix. 

(Interactive):1:1--1:1
 1 | (.suffix) : Nat -> Nat
Did you mean: Main.(.suffix)? (synchronous Idris2 evaluation failed
```

**Comment by michaelmesser** [comment]
I don't think this is a bug in Idris. Just a missing feature. The problem is that Idris needs a `typeAt` that doesn't take a name and returns the range to highlight on hover and the information to display. I think the editor is asking Idris for the type of `suffix` not the type of `(.suffix)`.

**Comment by ShinKage** [comment]
> This function would be useful too LSP as well.
The LSP server already returns the expected behaviour, as it uses the position and metadata to get the correct name.
We can probably consider the LSP implementation tested enough that we can upstream the behaviour into the compiler.

**Comment by ohad** [comment]
Could we please upstream this behaviour into the Idris2 compiler then, please, so that the IDE protocol/server could take advantage of it as well?

**Comment by michaelmesser** [comment]
LSP's hover still doesn't highlight the correct range for `x.y` (it highlights `x.y` instead of `x` or `.y`) and sometimes just shows `>>=` when hovering over a do block.

**Comment by gallais** [comment]
> `:typeat 6 13 (.suffix)` works in the REPL so I don't think this is a bug in Idris. 
   I think the editor is asking Idris for the type of `suffix` not the type of `(.suffix)`.

That's correct: the emacs mode uses `current-word` which relies on the syntax table to
identify what constitutes a word. Now, the problem is that if we include `.` as part of
a valid identifier then we'll get the whole `.fst.snd.fst` when asking for the type of
`.snd` which won't really help us...

So I believe the correct solution is to rely on the position to look up the attached
metadata and check that the returned identifier for that position has the same root
as the candidate. If there is no hit at that position (e.g. because we have not
reloaded the file since we've written the identifier) or there's a mismatch, then
we can default to looking up both `name` and `.name`.

**Comment by gallais** [comment]
The code in `Idris.REPL` is mostly correct. The main problem is that the idris
mode does not in fact send the position of the cursor when asking for the type
of the thing under it!

So it'll have to be a double fix.

**Comment by michaelmesser** [comment]
Why does `:typeat` require a name in the first place? Wouldn't it be better for Idris to figure out the name from the point?

**Comment by gallais** [comment]
If you haven't reloaded the file since you've written a function name then
it won't match whatever the map returns. The current mechanism then disregards
the map's answer and simply returns all the definitions in scope that have
a valid name.

This is pretty convenient to quickly get the type of an existing function
without switching to the REPL buffer and typing `:t name`.
