### ISSUE TITLE
Installing with Idris2 0.3.0 fails

### ISSUE THREAD

**Issue by gergoerdi** [idris-lang/Idris2#1788]
According to the documentation, any version of Idris 2 >= 0.2.2 should work for building Idris 2. However, I've just now tried on aa77b7f33e9b4bc14a2c9271735d0f5646fbd3fc and 0.3.0 fails to build `src/Compiler/Interpreter/VMCode.idr`:

```
$ ~/.idris2/bin/idris2 --version
Idris 2, version 0.3.0-eca25776c

$ make all IDRIS2_BOOT=~/.idris2/bin/idris2
67/202: Building IdrisPaths (src/IdrisPaths.idr)
Error: Module Data.SnocList not found

src/Compiler/Interpreter/VMCode.idr:14:1--14:21
 10 | import Compiler.VMCode
 11 | import Libraries.Data.IOArray
 12 | import Libraries.Data.NameMap
 13 | import Data.Nat
 14 | import Data.SnocList
      ^^^^^^^^^^^^^^^^^^^^

make: *** [Makefile:63: build/exec/idris2] Error 1
```

(this was after all `.ttc` files were removed.)

Building by starting from scratch (bootstrapping from the Scheme dump) works of course.

**Comment by gallais** [comment]
> According to the documentation, any version of Idris 2 >= 0.2.2 

Can you please point to the bit of the documentation stating this?

We only check on the CI that the current version can be built with the
latest *released* version and not any arbitrary version after 0.2.2 so
we should clearly not make that claim.

**Comment by gergoerdi** [comment]
It's in https://github.com/idris-lang/Idris2/blob/main/INSTALL.md#3-installing-with-an-existing-idris-2:

> ## 3: Installing with an existing Idris 2
> If you have an earlier version of Idris 2 (minimum version 0.2.2) installed:
> 
> ```
> make all
> make install
> ```

**Comment by mattpolzin** [comment]
IIRC, @edwinb hoped that we would not need to bump the minimum required compiler with every new release. This is why the CI explicitly sets the IDRIS2_VERSION environment variable and therefore needs to be manually changed when desired; otherwise the previous version could be determined automatically. 

If we want to keep to that plan, it sounds like the documentation has just fallen out of date about what version of the compiler is needed.
