### ISSUE TITLE
bad infinite loop that crashes at run time

### ISSUE THREAD

**Issue by reswatson** [idris-lang/Idris2#1828]
# Steps to Reproduce

(I am using 0.4.0)

Please enter, type check, then compile, and then run the following code:

```idris
mutual
  caseTest : Nat -> Bool
  caseTest p with (dummy)
  caseTest p | _ = True  
   
  dummy : Nat   
  dummy = case (caseTest 0) of
             True => 0 
             _ => 0 
  
main : IO ()
main = do 
       putStr (show dummy)
       putStr (show " END ")
```
# Expected Behavior

There are a number of options, but it should not pass type-checking and compilation and then crash. 

# Observed Behavior
Halts, then, terminal reports:
KILLED

**Comment by reswatson** [comment]
Sorry...I can't figure out how to enter code without it gobbling up the spacing.

**Comment by andrevidela** [comment]
use three backticks for code blocks : ```

**Comment by Z-snails** [comment]
When you say type-check, compile and run, do you mean that this example type-checks and compiles fine, but when you run the outputted program it loops forever?

ie
```bash
$ idris2 -o test <filename>.idr
$ ./build/exec/test
<loops forever>
```

If so, then that is expected behaviour.
The part of the compiler responsible for checking the program terminates is only enabled if you have `%default total` at the top of your file, or you mark an individual function with `total`
(eg
```
total
caseTest : Nat -> Bool
```)

If I remember correctly, Edwin has said he doesn't think a general purpose language like idris should have the default totality be total rather than covering, because once you get to higher order functions and recursion, it can get very tricky to show something is total.
But for proofs you absolutely should enable `%default total`

**Comment by reswatson** [comment]
```
%default total

mutual
  caseTest : Nat -> Bool
  caseTest p with (dummy)
                   caseTest p | _ = True  
   
  dummy : Nat   
  dummy = case (caseTest 0) of
                               True => 0 
                               _ => 0 
  
main : IO ()
main = do 
       putStr (show dummy)
       putStr (show " END ")
```

(i) Thanks for the help Andre 
(ii) I was taking %default total for granted as I personally always use it. I then add in 'partial' as a cheat, but very rarely. I made the silly mistake of thinking everybody would be doing the same thing - the code above is NOW presented correctly.
(iii) #653 uses 'partial' and the problem there is that it doesn't type check. This makes #1828 a very different and much worse bug even if it turns out that there is some common cause. What's happening for #1828 is that code that should be safe (because it not only type checks but also compiles - and is explicitly total) is crashing! 
(iv) Maybe this is only happening to me. Perhaps I have some versioning problem?...please try to replicate bug.

**Comment by gallais** [comment]
My bad, this is indeed not related to #1828. But this is indeed intended behaviour:
unless you turn on `%default total`, there is no guarantee that your code is safe.

**Comment by reswatson** [comment]
I had %default total, but had not made it explicit (next time I will!). I'll try again with the latest updates though and see if it is still a bug or not...hopefully you fixed it whilst fixing other stuff!

**Comment by reswatson** [comment]
I can confirm that the new main produces warnings and does not type check. Which is now expected behaviour.

**Comment by gallais** [comment]
Sorry about the confusion. Thanks for the report!
