### ISSUE TITLE
loss of multiplicity for linear functions in argument position

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#189]
Idris 2, version 0.2.0-7881dfd11
Really wasn't sure what to name this one.
# Steps to Reproduce
Observe the holes `foo1h , foo2h , foo3h` compared to their signatures.
```
infixr 6 -*
(-*) : Type -> Type -> Type
(-*) a b = (1 _ : a) -> b

foo1 : (((1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()) -> ()) -> ()
foo1 f = f ?foo1h

foo2 : (((1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()) -> ()) -> ()
foo2 f = f (id ?foo2h)

foo3 : ((a -* b -* c -* ()) -> ()) -> ()
foo3 f = f (id ?foo3h)
```
# Expected Behavior
All 3 holes have an expected type of `(1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()`
# Observed Behavior
All 3 holes have different types
```
   f : ((1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()) -> ()
-------------------------------------
foo1h : (1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()
```
```
   f : ((1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()) -> ()
-------------------------------------
foo2h : a -> b -> c -> ()
```
```
   f : ((1 _ : a) -> (1 _ : b) -> (1 _ : c) -> ()) -> ()
-------------------------------------
foo3h : a -> (1 _ : b) -> (1 _ : c) -> ()
```
I'm at a bit of a loss to describe the problem further than the hole types do, essentially I've defined f in the same way in 3 places and gotten different hole types to fill for each.
Why does id make foo1 and foo2 so different?
Why is -* making linearity be retained for `id` in `foo3`, but we then lose linearity just on argument `a`?

This isn't just an issue with id, that's just the simplest thing I could try. My discovery was actually when the foo holes were arguments to the Right constructor of Either.
e.g. `await (x :: xs) r = r (Right ?weirdhole)` but that required a more involved example type-wise.

**Comment by edwinb** [comment]
I've dug into this a bit, and I know what's going on now, but I don't have a solution yet. Not an easy one, anyway. It relates to this problem:

    test : a -> a -> a
    inc : Int -> Int
  
    foo : Int -> Int
    foo = test id inc

`id` and `inc` have different multiplicities, but there is a subtyping relationship on multiplicities in that it's fine to pass a linear function when an unrestricted one is expected, because there are no invariants to break, but not the other way around. So we can resolve `a` in the call to `test` with an unrestricted function. However, if `id` is checked first, unification commits too early to the linear version. We resolve this via a hack at the minute, which is to generalise to unrestricted multiplicity.

Unfortunately this hack breaks for the code in this issue. It still won't let code through which breaks the linearity on `f`, because once you fill in the hole the type checker has enough information to know what the type is supposed to be. But while the hole is there, it doesn't know because it's generalised the multiplicities.

Any proper, non-hacky solution, will involve delaying resolving the `a` argument to `test`. Ideally, multiplicities could also be variables that are solvable by unification, then in `test` we'd end up just having to solve `1` = `?mult`, but that is non-trivial to add.

I'll think on this more, but now I know it's not going to let linear things be used non-linearly (at least not for this reason) I don't know if I'll get to resolving it properly very soon.

**Comment by andrevidela** [comment]
> Ideally, multiplicities could also be variables that are solvable by unification

This sounds like the right way to go. Ideally I would love to have multiplicities depend on variables which themselves are bound with multiplicity `0` but I that would be a pretty big change from QTT.

For what it's worth I tried it with granule this is the equivalent idris code  in granule

```idris
test : forall {a : Type} . a [] -> a [] -> a []
test [v1] [v2] = [v2]

inc : Int [] -> Int []
inc [n] = [n + 1]

id : forall {a : Type} . a [] -> a []
id v = v

foo : forall {a : Type} . Int [] -> Int []
foo = test [id] [inc]
```

You'll notice everything uses the `[]` modality which is equivalent to the unrestricted default multiplicy in Idris.

This file compile because every type is unified to `Int []` without subtyping. Adding linearity back in any way results in errors like `Type 'Int' is not unifiable with the type 'Int [0..∞]'` which makes perfect sense.

**Comment by edwinb** [comment]
Given that the issue itself is all about display of hole types, it turns out there is a way to resolve it, which is to say that the hole types shouldn't have generalised multiplicities (we already do this in a few places, and actually probably ought to be the rule rather than the exception). I'll send a PR shortly.

Still, this is one to think about in the longer term.
