### ISSUE TITLE
Recursive function parametrised over interface causes compiler to loop

### ISSUE THREAD

**Issue by jcranch** [idris-lang/Idris2#1895]
# Steps to Reproduce

The following, while not particularly enlightening, is the sort of thing one might find oneself writing as part of a handwritten parser:

```
toBit : Num i => Char -> Maybe i
toBit '0' = Just 0
toBit '1' = Just 1
toBit _ = Nothing

-- Return the number represented in binary as an initial segment of
-- the string (remembering that if a number begins 0, it's zero).
eatBinary : Num i => String -> i
eatBinary = firstDigit . unpack where

  laterDigit : i -> List Char -> i
  laterDigit n [] = n
  laterDigit n (d :: ds) = let
    f : Maybe i -> i
    f Nothing = n
    f (Just a) = laterDigit (2*n + a) ds
    in f $ toBit d

  firstDigit : List Char -> i
  firstDigit [] = 0
  firstDigit (d :: ds) = let
    f : Maybe i -> i
    f Nothing = 0
    f (Just 0) = 0
    f (Just a) = laterDigit a ds
    in f $ toBit d
```

# Expected Behavior

Should probably compile. It does compile if you strip out the type variable "i" and replace it throughout with some particular instance of Num.

# Observed Behavior

The compiler appears not to terminate, though my patience is not infinite.

**Comment by edwinb** [comment]
Oh, this is interesting. The problem is the pattern match on `0`, which only works for concretely known `Num` because it has to run the appropriate `fromInteger` instance before it goes to the pattern match compiler. This works fine, provided you also add a constraint on `Eq i` in the parent function:

    firstDigit : List Char -> i
    firstDigit [] = 0
    firstDigit (d :: ds) = let
      f : Maybe i -> i
      f Nothing = 0
      f (Just a) = if a == 0 then 0 else laterDigit a ds
      in f $ toBit d
  
I don't plan to make this any nicer to write, I'm afraid, since it would involve making the pattern match compiler more complex than I'm willing to do. You should at least get a helpful error message here, and I'll see if I can work out what's making it take so long.
