### ISSUE TITLE
inconsistency folding with function taking lazy bool as second argument

### ISSUE THREAD

**Issue by FeldrinH** [idris-lang/Idris2#1904]
# Steps to Reproduce
Run
`foldl (&&) True [True, False]`
and
`foldr (&&) True [True, False]`

# Expected Behavior
Both return False

# Observed Behavior
`foldl` returns False, however `foldr` gives the following error: `Error: Can't solve constraint between: Bool and Lazy Bool.`

**Comment by buzden** [comment]
I'm sure this is expected behaviour (assuming rules of automatic delaying and forcing lazy values).

Look at the signature of `foldr`:
```
Prelude.foldr : Foldable t => (elem -> acc -> acc) -> acc -> t elem -> acc
```

The second argument of the result of the folding function have the same type, namely `acc`.

Look at the signature of `(&&)`:
```
Prelude.&& : Bool -> Lazy Bool -> Bool
```

They are not the same.

I.e., if you match them explicitly (1) or turn on automatic delaying addition (2), all typechecks:
```
-- (1)
foldr (delay .: (&&)) True [True, False]
-- (2)
foldr (\x, y => x && y) True [True, False]
```
both produce `Delay False` value.

**Comment by edwinb** [comment]
Yes, as @buzden says, this is expected. It is admittedly a bit odd, and a consequence of how we do `Lazy`, but it is doing what it's supposed to, so I'll close this.
