### ISSUE TITLE
readBufferFromFile is commented out

### ISSUE THREAD

**Issue by Riateche** [idris-lang/Idris2#209]
`readBufferFromFile` is commented out in the source code, so there is currently no way to load binary data from files partially. (There is `createBufferFromFile` but it can't be used for big files and doesn't allow to reuse the same buffer for multiple files.)

**Comment by edwinb** [comment]
All there is in the Buffer module is enough to make Idris 2 work. Patches welcome, I suppose :).

**Comment by edwinb** [comment]
Oh, I should add, that this one is commented out because there is a mismatch between C file handling (which we use everywhere else) and Scheme file handling (which we only use here). The reason for using Scheme in the back end for all of this is because there is a garbage collector question we haven't yet resolved, of how to (or even if we can) allocate memory in C and then have the runtime handle deallocation.

**Comment by melted** [comment]
You can use guardians for handling tasks on freeing of objects in Chez Scheme: there is an example of using it with C memory in the documentation https://cisco.github.io/ChezScheme/csug9.5/smgmt.html#./smgmt:h2

**Comment by edwinb** [comment]
I've just sent a PR that makes things a bit more flexible, so I'll close this when it's merged. I've ended up making `Buffer` a primitive that the FFI knows about, which will be much more flexible in general.

@melted We now have `GCPtr` which uses guardians to run a callback when the pointer is no longer accessible. I tried it for buffers, but it's quite slow, I think due to the overhead of calling C from Chez, so in the end I've kept the buffer manipulation as primitives. I think it's nice for this to be primitive in any case.
