### ISSUE TITLE
Expression search consumes all available memory

### ISSUE THREAD

**Issue by ultratwo** [idris-lang/Idris2#228]
Attempting to perform an expression search on `?help` in the following will consume all available memory almost instantly.

```idris
module Main

data Tree : (a : Type) -> Type where
  Node : a -> Tree a -> Tree a -> Tree a
  Leaf : a -> Tree a

foo : Tree Nat
foo = ?help
```

This is because `exprSearch` returns a list of all possible results (up to depth 5), even though the  current callers of `exprSearch` only use the first element of the list. This datatype has extremely large number of possible inhabitants, filling all of memory.

I'm proposing to fix this by:
1. Converting `exprSearch` to return a stream of results.
2. Converting `exprSearch` to do a depth first search, so that users get nice small expressions (e.g. search for `Tree ()` returns  `Leaf ()` rather than `Node () (Node () (Node () (Node () (Leaf ()) (Leaf ())) ...`)

Would you be interested in a pull request for this?

**Comment by ziman** [comment]
That sounds like a valuable improvement to me!

**Comment by edwinb** [comment]
I've been reorganising expression search so that instead of returning a list, it returns a result and a continuation. It turns out it needs to be a bit more complicated than returning a stream because of the way the context is organised (a mutable array, but we need to take care when backtracking so that we don't overwrite bits of the array when we shouldn't) and actually we weren't doing this right! There's a PR coming soon.

I hope I'm not treading on anyone's toes by fixing this, but it does need a bit of reorganisation anyway because I want to make the program search machinery available from elaborator reflection too.
