### ISSUE TITLE
Same (almost) kind of expressions lead to different results

### ISSUE THREAD

**Issue by Datoclement** [idris-lang/Idris2#2457]
# Steps to Reproduce
```idris2
Evident: x = x
Evident = Refl 

tail_neq: DecEq a => {xs, ys: Vect n a} -> (xs = ys -> Void) -> (x :: xs) = (y :: ys) -> Void
tail_neq xs_neq_ys Evident = ?myhole1

working_tail_neq: DecEq a => {xs, ys: Vect n a} -> (xs = ys -> Void) -> (x :: xs) = (y :: ys) -> Void
working_tail_neq xs_neq_ys Refl = ?myhole2
```
# Expected Behavior
The code should type check

# Observed Behavior
No. It did not. And the `working_tail_neg` alone did type check, which is confusing. Any thought?

Edit: add xs_neq_ys argument to the second function from @buzden

**Comment by buzden** [comment]
It seems that you have forgotten `xs_neq_ys` argument before the `Refl` in the second function example, or else it also does not typecheck (and shouldn't).

The first function should not typecheck because you are trying to match a function value `Evident` but you are allowed to match only on constructors and primitives, as the error message states.

Maybe, there is problem that `Evident` value seems to reduce to the normal form in the error message, thus leading to a strange error message
```
While processing left hand side of tail_neq. Can't match on Refl (Not a constructor application or primitive).
```
i.e. it prints a constructor  and complains that it is not a constructor.

So, behaviour of error presence is an expected behaviour, but error message could be better.

**Comment by Datoclement** [comment]
> It seems that you have forgotten `xs_neq_ys` argument before the `Refl` in the second function example, or else it also does not typecheck (and shouldn't).
> 
> The first function should not typecheck because you are trying to match a function value `Evident` but you are allowed to match only on constructors and primitives, as the error message states.
> 
> Maybe, there is problem that `Evident` value seems to reduce to the normal form in the error message, thus leading to a strange error message
> 
> ```
> While processing left hand side of tail_neq. Can't match on Refl (Not a constructor application or primitive).
> ```
> 
> i.e. it prints a constructor and complains that it is not a constructor.
> 
> So, behaviour of error presence is an expected behaviour, but error message could be better.

Oh, now I understand. Thank you very much!

**Comment by gallais** [comment]
We don't have pattern synonyms yet so you can't use `Evident` on the LHS.
