### ISSUE TITLE
Module Prelude not found with custom backend

### ISSUE THREAD

**Issue by locallycompact** [idris-lang/Idris2#2559]
Hi. I tried to follow the custom backend instructions here: https://idris2.readthedocs.io/en/latest/backends/custom.html

But I get the error

```
lc@nixos ~/idris2-backend-example (master)> ./result/bin/lazy-idris2
     ____    __     _         ___
    /  _/___/ /____(_)____   |__ \
    / // __  / ___/ / ___/   __/ /     Version 0.5.1-36918e6
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org
 /___/\__,_/_/  /_/____/   /____/      Type :? for help

Welcome to Idris 2.  Enjoy yourself!
With codegen for: lazy
Uncaught error: Error: Module Prelude not found

(Interactive):1:1--1:1
 1 |
```

Here's my reproduction:

https://github.com/locallycompact/idris2-backend-example

Problem occurs using:

```
nix build
./result/bin/lazy-idris2
```

**Comment by locallycompact** [comment]
I sort of have a fix for this now

**Comment by ColeDeanShepherd** [comment]
@locallycompact What was your fix?

**Comment by nukisman** [comment]
Does anyone know a solution? 😞

**Comment by mattpolzin** [comment]
The example from the original post for this issue actually uses a third party repo (https://github.com/claymager/idris2-pkgs) as a foundation. I’m not an expert in Nix but I’m particularly unfamiliar with the internals of that repository’s Nix flake. 

I do suspect i can lead you in the right direction, though. Idris 2 compilers need to be able to locate two builtin libraries (prelude and base); if you were to be basing your build off of the Idris 2 flake in this compiler repo, those libraries would be in the correct paths because of the following: https://github.com/idris-lang/Idris2/blob/main/nix/package.nix#L61

As a side note, if you’ve ever installed Idris 2 in another way (not via Nix), then following that with a Nix install can cause this same problem of not finding Prelude for a totally different reason. If you think you might be in that situation, let me know.

**Comment by nukisman** [comment]
@mattpolzin thanks for your response! 

I think I should make another issue because I have same problem in the another environment (w/o `nix` at all):
Please, check it out: https://github.com/idris-lang/Idris2/issues/2874
