### ISSUE TITLE
Inline documentation for constructor of record causes parse error

### ISSUE THREAD

**Issue by ayaye** [idris-lang/Idris2#2732]
# Steps to Reproduce

Compile the following example from https://idris2.readthedocs.io/en/latest/reference/documenting.html

```idris
module Documenting

||| We can document records, including their fields and constructors
record Yummy where
  ||| Make a yummy
  constructor MkYummy
  ||| What to eat
  food : String
```

# Expected Behavior

Successful compilation.

# Observed Behavior

```
Error: Expected end of input.

Documenting:5:3--5:19
 1 | module Documenting
 2 | 
 3 | ||| We can document records, including their fields and constructors
 4 | record Yummy where
 5 |   ||| Make a yummy
```

# Info

$ idris2 --version

`Idris 2, version 0.5.1-bc8b6bb7a`

**Comment by SalWolffs** [comment]
Looking into this a bit, the issue seems to be that `recordConstructor : OriginDesc -> Rule Name` (in src/Idris/Parser.idr) is not calling `optDocumentation : OriginDesc -> EmptyRule String`, which handles doc comments. So the grammar as the compiler implements it just doesn't contain doc comments for record constructors. Adding a call to `optDocumentation` is easy enough, but runs into another issue: `recordConstructor` is a `Name` parse rule. `Name`s (in src/Core/Name.idr) don't have a documentation field, and there isn't one set aside for documenting the constructor in `MkPRecord` (in src/Idris/Syntax.idr) either, so there would be nowhere to put the `String` read by `optDocumentation`.

At this point, since parsing documentation and then quietly dropping it seems like it can't be the intention, I can see roughly three options, in ascending order of involvement, of which I'd be inclined to do the second one but am not confident implementing (at least not without discussion):
1. Make the documentation (and specification) match the compiler's current behaviour, dropping separate documentation of record constructors on the basis that there's only ever one constructor for a record and its documentation can be folded into that of the constructor.
2. Add a constructor documentation field to `MkPRecord` (or the wrapping `PRecord`) and `PInterface` (all in src/Idris/Syntax.idr), make `recordConstructor : OriginDesc -> Rule (String, Name)`, and adjust the two functions in src/Idris/Parser.idr which call `recordConstructor` (`recordBody` and `ifaceDecl`) to properly put the docstring into those newly added documentation fields. The bit that has me worried is then finding and adjusting every place that interacts with `PDecl'` or `PDecl` (both are public export and contain those constructors) to correctly deal with (or ignore) those doc fields, including adding documentation-handling code.
3. Make `Name` take documentation in at least the `UN` (User-defined Name) case. This feels like both massive overkill, and inflicting a complexity burden on a lot of code that might not ever have a docstring to store. If this is the right approach, it seems like it'd be an entire rewrite of where docstrings are stored.

**Comment by gallais** [comment]
Definitely 2.
