### ISSUE TITLE
`MW` variables sometimes become `M0` during unification

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#2814]
In the following, `k'` is derived from `x` within `X_` and therefore should be `MW`, but idris thinks it's `M0`.

https://gist.github.com/redfish64/8ec7f6e49e2cf2d39ddd27b86a0fa969

```
data X : (x : Bool) -> Type where
  X_ : {x : Bool} -> X x

foo : X (not k) -> X k
foo (X_ {x=not k'}) = X_ {x=k'} -- k' should be `MW` here, but is `M0`
```

# Steps to Reproduce

Typecheck

# Expected Behavior

OK!

# Observed Behavior

```
- + Errors (1)
 `-- LearnLinearity6.idr line 5 col 28:
     While processing right hand side of foo. k' is not accessible in this context.
     
     LearnLinearity6:5:29--5:31
      1 | data X : (x : Bool) -> Type where
      2 |   X_ : {x : Bool} -> X x
      3 | 
      4 | foo : X (not k) -> X k
      5 | foo (X_ {x=not k'}) = X_ {x=k'} -- k' should be `MW` here, but is `M0`
```

**Comment by gallais** [comment]
`not` is a function, not a constructor so you cannot pattern-match on expressions of the form
`not k'`. What idris concludes is that your stating that this expression is forced which means it
does not bind any variable. The variable therefore has to be bound somewhere else, here
implicitly at the beginning of the LHS because `foo : X (not k) -> X k` really is `foo : forall k. (...)`.
And `forall` binds at quantity `0`.

What you probably want is something like:
```
foo : X (not k) -> X k
foo (X_ {x=k'})
  = rewrite notInvolutive k' {- or whatever the name of that lemma is -} in
     X_ {x=not k'}
```

**Comment by redfish64** [comment]
Ok, if that is the case, then it's inconsistent, in that if `x` is a `Nat`, this similar code works fine:

```
namespace B
  succ : Nat -> Nat
  succ k = S k

  data X : (x : Nat) -> Type where
    X_ : {x : Nat} -> X x

  foo : X (succ k) -> X k
  foo (X_ {x=(succ k')}) = X_ {x=k'} --this works fine
```

This is what led me to believe that idris lets you pattern match on functions.
