### ISSUE TITLE
CSE optimisation is tough with `%inline` and lazy meeting in the same place

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#2927]
# Steps to Reproduce

Run the following code:

```idris
import Data.List.Lazy

import Debug.Trace

%default total

%inline
(::) : Maybe a -> Lazy (LazyList a) -> LazyList a
Nothing :: xs = xs
Just x  :: xs = x :: xs

fufu : a -> Maybe a
fufu = Just

g : LazyList Nat
g = trace "--- outmost ---"
  [ fufu $ trace "pure 6" 6
  , fufu $ trace "pure 5" 5
  ]

main : IO Unit
main = printLn g
```

# Expected Behavior

Prints

```
pure 6
--- outmost ---
pure 5
[6, 5]
```

# Observed Behavior

```
pure 5
pure 6
--- outmost ---
[6, 5]
```

i.e. the value in the tail of the lazy list computes eagerly.

# Analysis

Thanks to @AlgebraicWolf who realised that the reason for this is CSE, which puts internals of the lazy value (tail of the list) to a top-level declaration, and thus it is computed too early.

We've realised that this behaviour goes away
- if you remove `%inline` of `::`, or
- if function `::` does not pattern match (say, if we use `Identity` instead of `Maybe`), or
- if you inline manually function `fufu`.

So, this is the minimal case we could find reproducing the problem.

Pinging @stefan-hoeck as the original author of the CSE optimisation. Do you understand what is going on in this case?

**Comment by AlgebraicWolf** [comment]
I have tried to further investigate the issue, and I think I have some understanding of what is going on. After all the inlining and constant folding, the expression for `g` looks something like this:

```
(Debug.Trace.trace
  ["--- outmost ---",
  (%case(Main.fufu [(Debug.Trace.trace ["pure 6", 6])])
    [
    (%concase [nothing] Prelude.Types.Nothing Just 0 []
      (%case (Main.fufu [(Debug.Trace.trace ["pure 5", 5])])
        [
        (%concase [nothing] Prelude.Types.Nothing Just 0 [] (%con [nil] Data.List.Lazy.Nil Just 0 [])),
        (%concase [just] Prelude.Types.Just Just 1 [{e:2}] (%con [cons] Data.List.Lazy.:: Just 1 [!{e:2}, (%delay Lazy (%con [nil] Data.List.Lazy.Nil Just 0 []))]))
        ]
        Nothing
      )
    ),
    (%concase [just] Prelude.Types.Just Just 1 [{e:2}]
      (%con [cons] Data.List.Lazy.:: Just 1
        [
        !{e:2},
        (%delay Lazy
          (%case (Main.fufu [(Debug.Trace.trace ["pure 5", 5])])
            [
            (%concase [nothing] Prelude.Types.Nothing Just 0 [] (%con [nil] Data.List.Lazy.Nil Just 0 [])), 
            (%concase [just] Prelude.Types.Just Just 1 [{e:3}] (%con [cons] Data.List.Lazy.:: Just 1 [!{e:3}, (%delay Lazy (%con [nil] Data.List.Lazy.Nil Just 0 []))]))
            ]
            Nothing
          )
        )
        ]
      )
    )
    ]
    Nothing
  )
  ]
)
```

Inlining of pattern-matching function `(::)` resulted in several occurrences of expression `(Main.fufu [(Debug.Trace.trace ["pure 5", 5])])`, and that expression is then lifted to the top level by CSE.

**Comment by AlgebraicWolf** [comment]
To sum up, after inlining expression appears both inside and outside of `%delay` in several branches of `%case`. This is not a problem by itself, as only one branch is executed, and order works as intended. This is not a problem, as expression exists outside of `%delay` only when it should be executed eagerly. However, when CSE comes into play, it lifts expression to toplevel definition, breaking order of computation.

This is a problem even if we disregard functions that are implemented using `unsafePerformIO`, as under `%delay` we might have a very large, or even diverging computation that would not be evaluated otherwise. 

To fix the issue, I've tried to modify CSE so that it would track occurrence of expression inside `%delay`, and for expressions that do occur it would simply not lift them to toplevel definition. This eliminated the bug, but bootstrapped compiler with the fix compiles `idris2api.ipkg` approximately 39% slower, and that would be unacceptable. I've also tried instead wrapping lifted expressions occurring inside `%delay` blocks as wrapped in `%delay` and forcing them at every use. Unsurprisingly, that didn't help.

Perhaps, the most efficient approach is to lift expressions as *memoized*, so that they are computed only on first use and the value is reused later if necessary. This, however, seems to require breaking changes to the compiler and support by all backends.

**Comment by buzden** [comment]
As @stefan-hoeck pointed [here](https://discord.com/channels/827106007712661524/827109190266257409/1092661024257220628) and I checked, this problem happens only on `chez` and `racket` backends, and most probable suspect is, actually, #2817. Possible solution can be switching to the approach from #2807.
