### ISSUE TITLE
`__LOC__` and `__FILE__` cause unexpected parse errors

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#2967]
```idris
main : IO ()
main = do
    _ <- pure ()
        | _ => putStrLn __LOC__
    pure ()
```
Or using `__FILE__`
# Expected Behavior
Compiles fine, as it does if you replace `__LOC__` with a string or a variable

# Observed Behavior
```
Error: Expected '=>' or 'impossible'.

error:4:13--4:15
 1 | main : IO ()
 2 | main = do
 3 |     _ <- pure ()
 4 |         | _ => putStrLn __FILE__
                 ^^
```

EDIT: as a work-around you can put brackets around `__LOC__` (ie `(__LOC__)`)

**Comment by dunhamsteve** [comment]
Adding a `debugString` alt to either `argExpr` or  `simpleExpr` fixes issues with using `__FILE__` as an argument, but it still fails with "unreachable clause", which seems correct.  Or is that somehow reachable?

**Comment by Z-snails** [comment]
No that's not supposed to be reachable. That's just a result of minimising the code I had

**Comment by dunhamsteve** [comment]
Ok. I think my PR will handle the issue, but the case above doesn't compile with the fix because of the unreachability.  

I was confused because the reduced test case you provided compiled successfully with a string in there and my fixed code complained about the unreachable branch. It turned out that the latest Idris detects the unreachable branch, but my LSP was old enough to accept it and write out a .ttc when I changed it to a string.

**Comment by Z-snails** [comment]
Thanks for the fix!
