### ISSUE TITLE
Projections out of a negative record are sometimes seen as total

### ISSUE THREAD

**Issue by 91khr** [idris-lang/Idris2#3030]
# Steps to Reproduce

Sorry for the long example and illustration, since I can't find something simpler to reproduce the error.

``` idris
module Test

namespace NS
  public export
  data Neg : Type where
    Nt : (Neg -> Neg) -> Neg

record RF infot where
  constructor MkRF
  info : infot
  op : Neg -> Neg

Functor RF where
  map f (MkRF info op) = MkRF (f info) op

Applicative RF where
  pure a = MkRF a id
  f <*> a = MkRF (f.info a.info) (f.op . a.op)

Monad RF where
  a >>= f = let res = f a.info in res
  join fs = ?fs
```

This would produce the following error:

``` text
Error: >>= is not total, possibly not terminating due to call to Test.RF

Test:21:1--23:16
 21 | Monad RF where
 22 |   a >>= f = let res = f a.info in res
 23 |   join fs = ?fs
```

Meanwhile, the following modifications would *not* produce such error:

- Define an interface with the same signature as Monad, and implement that interface for it:

  ``` idris
  interface Applicative m => SM m where
    (>>=) : m a -> (a -> m b) -> m b

  SM RF where
    a >>= f = let res = f a.info in res
  ```

  The `Applicative` constraint can be removed, and there's no error produced too.

- Define `Neg` in the same namespace as `RF`:

  ``` idris
  module Test

  data Neg : Type where
    Nt : (Neg -> Neg) -> Neg

  record RF infot where
    constructor MkRF
    info : infot
    op : Neg -> Neg

  -- The same as the full example above
  ```

- Remove the `let` expression:

  ``` idris
    Monad RF where
      a >>= f = f a.info
      join fs = ?fs
  ```

# Expected Behavior

Termination check either fails for all variants above, or successes for all of them.

**Comment by gallais** [comment]
Did you mean to start your file with `%default total`? Without it,
definitions will not be rejected if they are not terminating.

> Define an interface with the same signature as Monad

Note that in `prelude` the definition of `Monad` *demands*
that `(>>=)` is total which you are not doing here.

**Comment by 91khr** [comment]
>Did you mean to start your file with %default total? Without it,
>definitions will not be rejected if they are not terminating.

No, this is the whole file.

>Note that in prelude the definition of Monad demands
>that (>>=) is total which you are not doing here.

Sorry for not noticing this. However, the other two variants may be expected to have the same behavior as the original one.

**Comment by dunhamsteve** [comment]
What version of idris are you using?  That first block of code is not giving me an error when I place it in a file and run `idris2 --check Test.idr`. (It's working for me with 0.6.0-31c17ebec and 0.6.0-568ef8cb0.)

**Comment by 91khr** [comment]
> What version of idris are you using? That first block of code is not giving me an error when I place it in a file and run `idris2 --check Test.idr`. (It's working for me with 0.6.0-31c17ebec and 0.6.0-568ef8cb0.)

`0.6.0-870bc8243`.

**Comment by dunhamsteve** [comment]
Sorry, I mixed up the idr files, it is not working for me.

**Comment by dunhamsteve** [comment]
Here is a reduced case, where `blah` fails termination check and `blah2` passes.  The two functions are essentially the same, but a `let` statement is added to the marked non-total. Note that the record `RF` has one negative field and on positive, the negative one is not used in the functions.
```idris
record RF infot where
  constructor MkRF
  info : infot
  op : RF infot -> RF infot

total
blah : RF a -> (a -> RF b) -> RF b
blah a f = let foo = f a.info in foo

total
blah2 : RF a -> (a -> RF b) -> RF b
blah2 a f = f a.info
```
The totality checker picks up an additional reference to `Test.RF` - maybe because it is being passed into the `let` statement. 
```
Test.blah
...
Compiled: \ {arg:2}, {arg:3} => let foo = {arg:3} (case {arg:2} of  { Test.MkRF {tag = 0} [cons] {e:1} {e:2} => {e:1}}) in
foo
Refers to: Test.RF.(.info), Test.RF
Refers to (runtime): Test.MkRF

Test.blah2
...
Compiled: \ {arg:2}, {arg:3} => {arg:3} (case {arg:2} of  { Test.MkRF {tag = 0} [cons] {e:1} {e:2} => {e:1}})
Refers to: Test.RF.(.info)
Refers to (runtime): Test.MkRF
```

This version also fails totality checking - the _compiled_ tree is identical to the version that passes totality checking, but the compile time tree differs (passing the `RF` value through the `let`):
```idris
blah3 : RF a -> (a -> RF b) -> RF b
blah3 a f = let foo = a in f foo.info
```


```
Test.blah3
Compile time tree: let foo = {arg:2} in {arg:3} (foo .info)
Compiled: \ {arg:2}, {arg:3} => {arg:3} (case {arg:2} of  { Test.MkRF {tag = 0} [cons] {e:1} {e:2} => {e:1}})
Refers to: Test.RF.(.info), Test.RF
Refers to (runtime): Test.MkRF
```

**Comment by dunhamsteve** [comment]
Consider:
```idris
blah : RF a -> (a -> RF b) -> RF b
blah a f = let foo = f a.info in foo
```

With the `let` in there, there is an extra `Test.RF` in refersTo.   This ref is coming from the type on the binder for `let`, because `f a.info` is _returning_ an `RF b`, which is assigned to `foo`.  For most binders, I think this is right, because we're constructing an abstraction and that type appears in negative position. But with `let` I don't think it counts. And if you turn it into a proper function by adding a type declaration (see `blah4` below), then that type is its return type, and it passes the totality checker.

This patch fixes the issue, and I can PR it with a test case after CI completes, but I want someone smarter than myself to double check my reasoning. 

```
diff --git a/src/Core/TT.idr b/src/Core/TT.idr
index 47ae541c5..c7a645c1c 100644
--- a/src/Core/TT.idr
+++ b/src/Core/TT.idr
@@ -1843,7 +1843,7 @@ addRefs ua at ns (Meta fc n i xs)
     addRefsArgs ns [] = ns
     addRefsArgs ns (t :: ts) = addRefsArgs (addRefs ua at ns t) ts
 addRefs ua at ns (Bind fc x (Let _ c val ty) scope)
-    = addRefs ua at (addRefs ua at (addRefs ua at ns val) ty) scope
+    = addRefs ua at (addRefs ua at ns val) scope
 addRefs ua at ns (Bind fc x b scope)
     = addRefs ua at (addRefs ua at ns (binderType b)) scope
 addRefs ua at ns (App _ (App _ (Ref fc _ name) x) y)
```

As a workaround, you can use a local function by adding a type declaration in the `let`:
```idris
total
blah4 : RF a -> (a -> RF b) -> RF b
blah4 a f = let foo : RF b
                foo = f a.info
             in foo
```

**Comment by dunhamsteve** [comment]
Probably not a surprise, but as an additional data point, this issue occurs without record being involved:
```idris
data Oops = MkOops (Not Oops)

total
runOops : Oops -> Not Oops
runOops (MkOops nf) = nf

total
notOops : Not Oops
notOops x = runOops x x

oops : Oops
oops = MkOops notOops

total
boom : Void
boom = runOops oops oops
```
Inspecting with `:di`, Idris knows that `Main.oops` is covering and that `boom` references `Main.oops`. Explicitly adding `total` to `oops` causes it to fail, so it doesn't seem to be doing a totality check on `oops`.

I think the root issue is that we're relying on `SizeChange` to deal with the `Unresolved`, and it doesn't look at non-loops. I addressed this by having additional checks at the end of `calcTerminating`.

This causes a change in the results of the test `positivity004`. Idris additionally notices that `argh : Void` and `notF : Not F` are not total, I believe this is correct. 

The change also breaks `libs/papers/Data/Recursion/Free.idr` because Idris is now upset that `Mu` (from `DybjerSetzer`) is not total:
```
Error: evaluate is not total, possibly not terminating due to call to Data.InductionRecursion.DybjerSetzer.Mu
```
which takes a Mu as an argument:
```idris
evaluate : (f : PiG a b) -> (i : a) -> Mu (Domain f) i -> b i
evaluate f i inDom = Decode inDom
```
`Mu` is defined as:
```idris
data Mu : (f : (s : sort) -> Code input (input s)) -> (s : sort) -> Type where
  MkMu : {f : (s : sort) -> Code input (input s)} -> {s : sort} ->
         DecodeType (f s) (Mu f) Decode -> Mu {input} f s
```
Adding an `assert_total $` before `Decode` in `evaluate` resolves the issue, but I'm not sure if the original error is correct. 

You can find my proposed changes here: https://github.com/idris-lang/Idris2/compare/main...dunhamsteve:Idris2:totality-3030

If it's not completely wrong, I can PR for further discussion.

**Comment by dunhamsteve** [comment]
That change also determined that `resetProofState` in `Idris.Repl.Opts` is not total. It's updating a field with non-total type (`Maybe (Name, Core (Search RawImp))` where `Search a = Tap Core` and `Tap` is `covering`).

**Comment by gallais** [comment]
Yeah `Mu` will definitely not be seen as total because we are not tracking
whether functions like `DecodeType` use their arguments in a strictly positive
manner.

Now that we actually support `assert_total` in inductive definitions, I would
just do
```
MkMu : {f : (s : sort) -> Code input (input s)} -> {s : sort} ->
         assert_total (DecodeType (f s) (Mu f) Decode) -> Mu {input} f s
```
