### ISSUE TITLE
Source file "Main.idr" is not in the source directory when invoking compiler with `--source-dir`

### ISSUE THREAD

**Issue by phischu** [idris-lang/Idris2#3224]
# Steps to Reproduce

When in a folder `MyProject` create a file `src/Main.idr` with content

```
module Main
```

Invoke the compiler with

```
idris2 --source-dir src Main.idr
```

# Expected Behavior

The file is successfully loaded and the REPL greets me with

```
Welcome to Idris 2.  Enjoy yourself!
1/1: Building Main (Main.idr)
Main>
```

# Observed Behavior

An error message:

```
Uncaught error: Error: Error: Source file "Main.idr" is not in the source directory "/path/to/MyProject/src"
```

This is puzzling, since there is a file `Main.idr` in directory `/path/to/MyProject/src/`.

**Comment by buzden** [comment]
Look, when you have a `sourcedir` set in your `.ipkg` file, whould you expect `idris2` command to take `Main.idr` or `src/Main.idr` as an argument? It takes `src/Main.idr` because it is a **path for a file**.

The same is here. Command argument `--source-dir` sets the root, but the argument still needs to to be a path to a file, not a relative something. So, I'd consider observed behaviour to work as expected.

Strictly speaking, `--source-dir` determines which prefix of a file path to drop before converting directory paths to modules.

**Comment by phischu** [comment]
Thank you, this was a misunderstanding on my side. Sorry for the noise.

> Strictly speaking, --source-dir determines which prefix of a file path to drop before converting directory paths to modules.

And also the other way round, when converting imported module names to directory paths.
