### ISSUE TITLE
Equal Operator `(=)` treated as parsing error.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris2#367]
# Steps to Reproduce

Given the following Idris2 file:

```idris
module TypeLevel

import Decidable.Equality

data Foo : (type : Type)
        -> (p : type -> type -> Type)
        -> Type
  where
    Bar : (x,y : type) -> p x y -> Foo type p

bar : Foo Nat (=)
```

# Expected Behavior

I would expect the file to type check and tell me that `bar` lacks a definition.

# Observed Behavior

The following error is presented:

```sh
- + Errors (1)
 `-- TypeLevel.idr line 11 col 14:
     Parse error: Not the end of a block entry (next tokens: [symbol (, symbol =, symbol ), end of input])
```

This appears to be an issue with the parser in which an operator, that is eta-reduced, is not expected, where as it ought to be.

We also see unexpected behaviour when comparing the following code snippets in whic

+ this works:

```idris
Equal : Type -> Type -> Type
Equal a b = a = b

bar : Foo Nat Equal
```

+ but not this:
```idris
Equal : Type -> Type -> Type
Equal = (=)

bar : Foo Nat Equal
```

**Comment by fabianhjr** [comment]
I dont really understand why you are using `=` instead of `Equal` (`===` or `~=~`), tried it with the last one on master and it typechecks.

```
import Decidable.Equality

data Foo : (type : Type)
        -> (p : type -> type -> Type)
        -> Type
  where
    Bar : (x,y : type) -> p x y -> Foo type p

bar : Foo Nat (~=~)
```

As far as I understand the use of `=` by itself shouldn't be legal idris there since it isn't available as a value/constructor. (`Equal` is and `===` and `~=~` are)

**Comment by fabianhjr** [comment]
In particular, the symbol `=` is not treated as an operator:

https://github.com/idris-lang/Idris2/blob/176f2516da549c2daedf1fcb59cdd11bda5a3783/src/Parser/Rule/Source.idr#L126-L135

**Comment by melted** [comment]
So, it's the case where `=` is successfully used that is the error?

**Comment by jfdm** [comment]
Right, first:

> I dont really understand why you are...

Comes across as more condescending as you might have not originally realised. It would be better to take a more deferential tone and less argumentative when responding to issues. Assuming that you don't understand why I am not doing `x` can be rather insulting.

Now back to the issue at hand: Coming from Idris1, `(=)` is an identifier for equality that is available for use at the type-level thus there is prior expectation about type-level use of `(=)`. Granted we are using Idris2 in which we see that `(=)` is indeed presented at the type-level as a synonym for type-level equality. [We see that later on in `Builtins.idr`](https://github.com/idris-lang/Idris2/blob/176f2516da549c2daedf1fcb59cdd11bda5a3783/libs/prelude/Builtin.idr#L158). Now without realising that type-level equality is now defined as `Equals` (changes files that I have read do not make mention of this) and seeing what one assumes to be syntactic sugar buried in the the compiler for mapping `(=)` to `Equal` then there are *understandable* reasons to expect that can be used as `(=)` operator.

So we can either resolve this by:

1. ensuring that the documentation for Idris2 includes explicit note about the compilers builtin syntax sugaring; 
2. removing syntax sugar support for `(=)` and replace all occurrences with `(===)`. Idris2 is still nascent enough to allow this; or
3. extend syntax sugar in Idris2 to support use of eta reduced `(=)` .

**Comment by edwinb** [comment]
`=` is a bit special in the parser since, as well as being an operator, it's used in definitions as `lhs = rhs`. I can't remember if this worked in Idris 1, which also had to treat it specially for the same reason.

While Idris 2 is still new, we shouldn't be making changes that involve huge incompatibilities with Idris 1. There are a few due to the change in the core language and reorganisation of libraries, but I think we've nore or less spent our "gratuitous incompatibility" budget (necessary incompatibilities are fine :)). So if there's a decision to be made, looking at what Idris 1 does can be useful.

**Comment by fabianhjr** [comment]
Sorry @jfdm, didn't want to come across as condescending. I wanted to check and understand the rational before making a suggestion or pull request since I was unsure on whether it should be allowed. I believe instances of `(=)` could be recognized like on type signatures as aliases for `===` or `~=~` without much problem, however, this might cause problem/confusion with assignment.

I would be more inclined to suggest the first option you suggested along a better error message from the parser; however, since the issue report expected it to typecheck and work, I was wondering if there was a use-case that might be desirable to cover; the example you provided seems very close to the Equal in builtin so I wanted to check if you encountered this problem elsewhere.

**Comment by jfdm** [comment]
@edwinb I have Idris1 code with indexed types that have `(=)` as an argument. This is not surprising given [the definition of `(=)` in Idris1](https://github.com/idris-lang/Idris-dev/blob/8362faae469ebfed492635bf2219035e04b14932/src/Idris/AbsSyntaxTree.hs#L1542-L1578). It is **just** a data type declaration, and thus explains how I can use it in Idris1. My understanding that in Idris2 how `(=)` is defined is more analogous to how Dependent Pair's and their sugar are defined: Definition in libs, sugar in the compiler. This explains how I cannot use it in Idris2.

> While Idris 2 is still new, we shouldn't be making changes that involve huge incompatibilities with Idris 1. There are a few due to the change in the core language and reorganisation of libraries, but I think we've nore or less spent our "gratuitous incompatibility" budget (necessary incompatibilities are fine :)).

I think the situation in Idris2 over how `(=)` is defined is much improved, but I think we could move away from using `(=)` and use `Equals` and the operators,  removing support for the sugar `(=)` completely. Controversial, but I think we can get away with it. Idris1 is right but wrong.

@fabianhjr It is fine. The 'use case' is  being able to use a dependently typed data structure to hold predicates, one of which could be the equality predicate. For instance: `All xs ((=)3)` or `DPair Nat (3=)` or `DPair Nat (\x => x = 3)`. These all work in Idrtis1 and either should work in IDris2 given that `(=)` exists or should we break backwards compatibility in which `DPair Nat (\x => x = 3)` is only allowed. 

The issue here *really* is that Idris2 provides inconsistent use of `(=)` and Idris1 does not. A decision needs to be made on how to go forward.  TBH I can fix this, but need to know in which direction to go.

**Comment by gallais** [comment]
> removing support for the sugar `(=)` completely. Controversial, but I think we can get away with it. 

I also think this would be an improvement.

#136 is currently stuck because of the weird interplay of `=` for
definitions and `=` for the equality type. This confusing overloading
means some things parse at the moment by failing late after confusing
one for the other, rewinding and then attempting another parse. It's
not ideal. :/

**Comment by nickdrozd** [comment]
In Idris 1, it was [possible to prove things](https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Decidable/Order.idr#L46) about `(=)`:

```idris
Preorder t (=) where
  transitive _ _ _ = trans
  reflexive _ = Refl

Equivalence t (=) where
  symmetric _ _ = sym

Congruence t f (=) where
  congruent _ _ = cong
```

I would like to do something similar with https://github.com/idris-lang/Idris2/pull/314, but it wasn't possible when I last checked. Personally I thought it was pretty cool when I first saw the `(=)` relation proofs, so I consider it a bug that it can't be done yet in Idris 2.

**Comment by buzden** [comment]
> In Idris 1, it was [possible to prove things](https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Decidable/Order.idr#L46) about `(=)`:
> 
> ```idris
> Preorder t (=) where
>   transitive _ _ _ = trans
>   reflexive _ = Refl
> 
> Equivalence t (=) where
>   symmetric _ _ = sym
> 
> Congruence t f (=) where
>   congruent _ _ = cong
> ```

You can do this in Idris 2 with non-special syntactically name for propositional equality, namely `Equal`:

```idris
interface Preorder t (po : t -> t -> Type) where
  transitive : (0 a, b, c : t) -> (0 _ : po a b) -> (0 _ : po b c) -> po a c
  reflexive : (0 a : t) -> po a a

interface Preorder t eq => Equivalence t (eq : t -> t -> Type) where
  symmetric : (0 a, b : t) -> (0 _ : eq a b) -> eq b a

interface Equivalence t eq => Congruence t (f : t -> t) (eq : t -> t -> Type) where
  congruent : (0 a, b : t) -> (1 _ : eq a b) -> eq (f a) (f b)

Preorder t Equal where
  transitive _ _ _ = trans
  reflexive _ = Refl

Equivalence t Equal where
  symmetric _ _ = sym

Congruence t f Equal where
  congruent _ _ = cong f
```

There can be difficulties with 0s and 1s in the interface definition (look at arguments for `congruent` in this example), but this is a separate question. At least, definition above works:

```idris
abba : (0 _ : a = b) -> b = a
abba = symmetric a b -- typechecks
```

**Comment by nickdrozd** [comment]
@buzden Thanks, I didn't know about `Equal`, and I added it to that PR. Still, it seems like a poor substitute for proving facts about `(=)`. Are they really the same? It would be nice to prove that a property that holds of `Equal` also holds of `(=)`, but of course that isn't possible because of this very bug.

**Comment by gallais** [comment]
It's more than 1 year old now so I'll mark this as wontfix in the name of the big equal lobby: use `===`!
