### ISSUE TITLE
Can't resolve constraints in type

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#378]
In Idris1 this compiles (part of the base library, exact copy-paste):
```idris
vectAppendAssociative : (xs : Vect xLen elem) ->
                        (ys : Vect yLen elem) ->
                        (zs : Vect zLen elem) ->
                        xs ++ (ys ++ zs) = (xs ++ ys) ++ zs
```

In Idris2 (latest commit) it does not:
```
Can't solve constraint between:
	?xLen [no locals in scope]
and
	plus ?xLen ?yLen
at:
6	                        xs ++ (ys ++ zs) = (xs ++ ys) ++ zs
	                                           ^^^^^^^^^^^^^^^^
```
Explicitly introducing implicit length parameters produces:
```
Can't solve constraint between:
	plus xLen yLen
and
	xLen
at:
6	                        xs ++ (ys ++ zs) = (xs ++ ys) ++ zs
	                                           ^^^^^^^^^^^^^^^^

```

# Steps to Reproduce
Try to typecheck this:
```idris
import Data.Vect

vectAppendAssociative : {xLen, yLen, zLen : _} -> (xs : Vect xLen elem) ->
                        (ys : Vect yLen elem) ->
                        (zs : Vect zLen elem) ->
                        xs ++ (ys ++ zs) = (xs ++ ys) ++ zs
```

# Expected Behavior
It is more of a question than an issue statement.
Why this happens ?
How to write the type of `vectAppendAssociative` ?
I also tried to do rewriting in type and managed to typecheck the type.
But failed to prove it...

**Comment by edwinb** [comment]
It's because `=` is giving you homogeneous equality, but the types on the left and right of the `=` are different. This works, because `~=~` is explicit that the types on the left and right can be different:

    vectAppendAssociative : 
                          (xs : Vect xLen elem) ->
                          (ys : Vect yLen elem) ->
                          (zs : Vect zLen elem) ->
                          (xs ++ (ys ++ zs)) ~=~ ((xs ++ ys) ++ zs)

After that, the Idris 1 definition goes through fine. Idris 1 works harder to disambiguate things, which means some things are neater to write, but the cost is complexity in the elaborator and sometimes a performance hit.

At some point, I'll get around to implementing dependent rewrite, and then I might see if the `=` syntax can be made a bit cleverer, but otherwise if you need heterogeneous equality for the moment you'll need to be explicit about it.

**Comment by Russoul** [comment]
Ah, I should have guessed it...
Now it’s clear.
Thanks for answering !

**Comment by Russoul** [comment]
@edwinb I am really sorry to bother you once more...
But I have spent like 2 days in attempts to prove this, using heterogenous equality of course. No luck so far. I searched the net for examples of proving properties using heterogeneous equality, found none or too obvious at most. Also Vect.idr in Idris 2 lacks the implementation... Would you be so kind to prove this one please ?  Will do my best to do as much contribution as I can in return :P

P.S not sure if the issue tracker is the best place to ask for this. Asked at Stack Exchange before, absolute silence :)

**Comment by ziman** [comment]
This typechecks here.
```idris
import Data.Vect

lemma : {xs : Vect xn a} -> {ys : Vect yn a}
    -> xs = ys
    -> x :: xs = x :: ys
lemma Refl = Refl

assoc
  :  (xs : Vect xn a)
  -> (ys : Vect yn a)
  -> (zs : Vect zn a)
  -> (xs ++ (ys ++ zs)) ~=~ ((xs ++ ys) ++ zs)
assoc [] ys zs = Refl
assoc (x :: xs) ys zs = lemma $ assoc xs ys zs
```
I got there by starting with a hole on the RHS of `assoc`, case-splitting on `xs`, and then lifting the lemma out. You have to write your own `lemma` because even though `cong` looks like it would work here, it won't help you with differently typed sides. Perhaps you got pwned by that?

**Comment by ziman** [comment]
Other places to get help would be the #idris IRC channel on freenode or the #idris channel on the FP slack; the links are on the title page of https://idris-lang.org. :)

**Comment by Russoul** [comment]
@ziman Exactly ! Tried to write a different version of it (`cong`) that would allow heterogeneity but that would always result in unification mismatches. Same thing happened matching on the result of the recursive hypothesis... Anyways, nice solution, thanks a lot !
