### ISSUE TITLE
%transform not unifying variables as far as expected/desired

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#398]
idris2 1.3.2-git:0417c53fb
# Steps to Reproduce
```idris
%transform "foo" map {f=List} id x = x
```
```idris
%transform "biz" foldr {t=List} k z (map g xs) = xs
```
# Expected Behavior
Compilation succeeds.
# Observed Behavior
```
While processing right hand side of foo at src/Foo.idr:71:1--71:39:
When unifying List a and List b
Mismatch between:
	a
and
	b
at:
71	%transform "foo" map {f=List} id x = x
	                                     ^
```
```
While processing left hand side of $resolved1355 at src/Foo.idr:73:1--73:52:
Can't solve constraint between:
	?f ?b
and
	List ?elem
at:
73	%transform "biz" foldr {t=List} k z (map g xs) = xs
	                                     ^^^^^^^^
```
Supplying f for the latter, `%transform "biz" foldr {t=List} k z (map {f=List} g xs) = xs`, gets around this (though issue #397 then occurs) but I would have expected it to unify that on its own.

**Comment by edwinb** [comment]
In the first case, it's treating `id` as a variable following the usual rules. You need `Basics.id` instead (this really should be `Prelude.id` but the prelude is now split into several modules and the namespaces are wrong for the moment...)

In the second, that's a reasonable unifiication error, because it can't in general unify a hole application `?f ?b` with anything, even a constructor. It only works when resolving interfaces because we keep track of which variables are required for the search that arise from (invertible) interface definitions. There's no interface resolution happening, however, since we don't do that on a LHS. So it's irritating (sorry) but it is expected.

**Comment by MarcelineVQ** [comment]
Aha caught by the variable convention again :>
Thanks for the explanations.
