### ISSUE TITLE
Mutatio syntax introduces unsolved holes for records with more than one implicit field

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#429]
Follow-up to #421

# Steps to Reproduce
```idris
$ cat Foo.idr 
record Foo where
  constructor MkFoo
  {Gnu : Char}
  {Fnu : Char}

AFoo : Foo
AFoo = MkFoo {Gnu = 'c'} {Fnu = 'd'}


Bar : Foo
Bar = record {Gnu = '?'} AFoo
```

# Expected Behavior

Type-check fine

# Observed Behavior
```
$ idris2 -c Foo.idr 
1/1: Building Foo (Foo.idr)
Foo.idr:11:7--11:30:Unsolved holes:
Main.{_:234} introduced at Foo.idr:11:7--11:30
```

**Comment by edwinb** [comment]
Yes, indeed. As discussed on Slack, this is because in a record update, explicit arguments get explicitly added on the rhs, and implicit arguments get updated as `_` and the elaborator solves it by unification. So in your program you get:

    Bar = case AFoo of
                MkFoo {Gnu=_} => MkFoo {Gnu='?'} {Fnu=_}

To work out which implicits need to have their value explicitly propagated, and which can have implicits, involves either knowing in advance which values are going to be unifiable, or perhaps having a high level syntax for "unify but add a default if it's unsolved" but there's already lots of things going on with implicits and I'm reluctant to add more.

In the end, the problem is that you have implicit arguments but nothing depends on them so there's no help for the unifier. So I'm going to flag this as "expected behaviour".
