### ISSUE TITLE
Reflection from a different module: Can't reify as String at:

### ISSUE THREAD

**Issue by mb64** [idris-lang/Idris2#443]
I tried out the new reflection system by trying to generate the `(==)` function, and I ran into a strange issue where it would work if the code was all in one module, but not when you tried to use it from a different module.

See [this gist](https://gist.github.com/mb64/9786d6d9583276a718316aa6b3f85487) for the code.  `DerivingEq.idr` compiles and works just fine, but trying to use `genEq` from `test.idr` results in the message:
```
2/2: Building test (test.idr)
:1:1--1:1:While processing right hand side of == at test.idr:12:3--13:1:
Can't reify as String at:

```

I tried to minimize the example, but this small case works just fine:
<details>
<summary>Small case</summary>
<p>

```idris
-- A.idr
module A

import Language.Reflection

public export
makeFour : Elab Int
makeFour = check `(4)
```
```idris
-- B.idr
module B

import A
import Language.Reflection

%language ElabReflection

four : Int
four = %runElab makeFour
```
```shell
$ idris2 B.idr 
-- snip --
Welcome to Idris 2.  Enjoy yourself!
1/2: Building A (A.idr)
2/2: Building B (B.idr)
B> four
4
```
</p>
</details>

So it's not some fundamental issue with modules.

**Comment by MarcelineVQ** [comment]
I'm having a similar issue that seems related since it appears under the same circumstances
I've tests here
https://github.com/MarcelineVQ/idris2-elab-deriving/blob/master/src/Language/Elab/Deriving/EqTest.idr
that used to be in
https://github.com/MarcelineVQ/idris2-elab-deriving/blob/master/src/Language/Elab/Deriving/Eq.idr
They worked when located in Eq.idr but compilation fails when moved to EqTest.idr with vague errors of
```
Bad elaborator script lookupName (UN "MyNat") at:
110	%runElab deriveEq Export  `{{MyNat}}
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
lookupName is from https://github.com/MarcelineVQ/idris2-elab-deriving/blob/master/src/Language/Elab/Syntax.idr#L127

Don't mind the comments in the modules, they're not relevant, and just thoughts I've had during development.

**Comment by edwinb** [comment]
I've done a bit of poking, and by accident I found that it works if you make this change:

          let xs = map (\i : Integer => "x_" ++ show i) $ take nArgs [1..]
          let ys = map (\i : Integer => "y_" ++ show i) $ take nArgs [1..]

That is, being explicit that `i` is an `Integer` rather than having it be inferred by the default `Num`. It looks like, without that, it's not exporting the result of the search for the dictionary. I don't yet understand why it would behave like that, since it is supposed to save every search result in the `.ttc`. At least it's a clue.

**Comment by edwinb** [comment]
In fact it does save the results, but not recursively if the results are complicated enough. Oops! It's a bit surprising this hasn't come up before. I'll do something about this this evening as long as I'm the right sort of bored (likely).

**Comment by edwinb** [comment]
heh, in fact it's dafter even than that - it does go recursively, but too early, meaning that if some part of elaboration has been delayed for whatever reason (say, inability to resolve an interface yet) it doesn't build the complete list of names. Hopefully this'll fix both examples.
