### ISSUE TITLE
Lua backend

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#460]
It needs some extensive testing, but looks good yet.

It has two lua package dependencies: `bigint` and `lua-utf8`.
Both are shipped as submodules in backend repo.
`lua-utf8` is installable separately via `luarocks`,
`bigint` is not, plus looks like it has bugs, thats why I chose to ship its forked and fixed version.

Ideally, all you have to do to use it is `make all && make install`
Works for me (macOS), but I can imagine something going wrong on windows...

Please, have a look: https://github.com/Russoul/idris2-lua.git

**Comment by edwinb** [comment]
Nice, I'll give it a go! I have been interested in trying out Lua as a possible back end.

As with Idris 1, I'd rather not include all the backends in the Idris 2 distribution itself, since it's a lot to maintain and realistically I'd need to know at least basically how they all work. But perhaps we should start cataloguing them on the web site, along with a description of how complete they are (ability to build Idris 2 is a good test of completeness :)).

**Comment by Russoul** [comment]
@edwinb Okey still a bit to go until it can build Idris2 itself, needs a bit more optimisation. Recent Javascript backend was a great help to get me started. Also, wanted to ask you about `PrimIO.prim__schemeCall`. It is supposed to call functions of current backend right ? So its not scheme-only ? Maybe rename it then ?

**Comment by melted** [comment]
Non-scheme backends have to fake it, it's a limited number of calls in the libraries so doable. But ideally, `schemeCall` should be replaced where ever it is: https://github.com/idris-lang/Idris2/issues/446. But of course, other backends can't expect that there is a foreign declaration for them, so they still have to do a translation from the C one.
