### ISSUE TITLE
Parse error declaring constructor with the same name as type

### ISSUE THREAD

**Issue by mb64** [idris-lang/Idris2#504]
This works in Idris 1, or if I change it from `String` to `Strang`.
```idris
$ cat example.idr 
-- One type constructor, called String
data Thing = String
$ idris --nobanner example.idr 
*example> :t Main.String
String : Thing
*example> 
Bye bye
$ idris2 --no-banner example.idr 
1/1: Building example (example.idr)
example.idr:2:1--2:1:Parse error: Couldn't parse declaration (next tokens: [data, identifier Thing, symbol =, identifier String, end of input])
Main> 
Bye for now!
$ idris2 --version
Idris 2, version 0.2.0-80f4ced38
```

I would expect it to succeed like in Idris 1, or at least give a more descriptive error than `Parse error`.

I have 80f4ced38, which is a few weeks old, so I'll rebuild master and see if it does the same thing.

**Comment by gallais** [comment]
`String` is now considered a *reserved* name in the parser, cf:

https://github.com/idris-lang/Idris2/blob/master/src/Parser/Rule/Source.idr#L174-L177

So I think that's a "won't fix".

Admittedly the error message could be clearer. In case you try to name a constructor
after an already taken type (e.g. defining `data A = A`), you get:

> DataDecl.idr:3:10--5:1:DataDecl.A is already defined

rather than a raw parse error.

**Comment by gallais** [comment]
The current parse error is, I think, satisfactory:

```
1/1: Building Issue504 (Issue504.idr)
Error: Couldn't parse any alternatives:
1: Can't use reserved name String.
Issue504:1:14--1:20
 1 | data Thing = String
                  ^^^^^^
... (1 others)
```
