### ISSUE TITLE
PreorderReasoning certifies bogus proofs

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#536]
# Steps to Reproduce
```idris
$ cat Proof.idr 
import Syntax.PreorderReasoning

bad : 0 = 1
bad  = Calc $ |~ 0 ~~ 0 ...(Refl)

worse : "hello" ~=~ (\x:Nat => x)
worse = Calc $ |~ "hello" ~~ "hello" ...(Refl)
```
# Expected Behavior
Type error.
# Observed Behavior
```
$ idris2 -p contrib -c Proof.idr 
1/1: Building Proof (Proof.idr)
$
```

**Comment by edwinb** [comment]
Here's what I've found out so far. There's a suspicious looking thing in `Syntax.Preorder`:

    Calc {y} ((~~) {z=y} {y=y} der (y ** Refl)) = Calc der

It's suspicious because of the type of `~~`:

    (~~) : FastDerivation x y -> (step : (z : c ** y ~=~ z)) -> FastDerivation x z

...where there's two different `z`s (the one in the return type is out of the scope of the one bound in the dependent pair) and there is no reason that `z` and `y` should unify as is apparently expected in the clause in `Calc`. So, I think that clause in `Calc` should be rejected.

**Comment by edwinb** [comment]
Hmm, no, in fact `Calc` is fine since it can look at the expected type. Something is causing it to skip a unification step, though. I'll dig deeper later.

**Comment by edwinb** [comment]
Okay, there's a thing that's going wrong when it checks the repeated variable names on the LHS in `Calc`. If it's valid to repeat `y`, then you should also be able to say:

    Calc {y} ((~~) {z=_} {y=_} der (MkDPair _ Refl)) = Calc der

That is, replacing all but one with an `_` (the non-linear variable check is supposed to do something more or less like that). However, what you get is:

    Mismatch between:
	    _
    and
	    y
    at:

So, I've changed my mind again! `Calc` is the culprit, and that makes sense because all the other applications are fully rechecked so the most likely problem is an invalid LHS ...and I can see a point where, in the non-linear check, it's solving a thing it's not supposed to.

This reminds me that I usually have a policy of not speculating about the cause of an issue, but only commenting once I have a good idea what's going on. I'd better go back to that :).

A problem, though, is that I can't easily fix this one without breaking `Syntax.Preorder`. So I think we need a valid `Calc` first.

**Comment by ohad** [comment]
OK, [here's a proposed fix](https://github.com/idris-lang/Idris2/compare/master...ohad:preorder-reasoning) to `PreorderReasoning`. stdlib seems to go through fine with it, but I want to push it through frex first.

Sorry for the bug there --- it's really embarrasing!

That doesn't help us understand what was wrong with Idris, does it? 
Only that once we fix Idris, we have a correct `PreorderReasoning` to work ith.

**Comment by edwinb** [comment]
It was only by finding what was wrong with Idris that I found the problem with Calc, so I think it's resolvable :)

**Comment by gallais** [comment]
> Sorry for the bug there --- it's really embarrasing!

Finding proofs of false silently accepted by the system is a very
respectable sport. Nothing to be embarrassed about!
