### ISSUE TITLE
Function names are not resolved and get 0 quantity

### ISSUE THREAD

**Issue by andorp** [idris-lang/Idris2#539]
I tried to reproduce the following blog post in Idris2: https://sitr.us/2014/05/05/category-theory-proofs-in-idris.html but got `is not accessible` error, for a defined function.

# Steps to Reproduce
Example program:
```
idF : a -> a
idF = id

extensionality : (f : a -> b) -> (g : a -> b) -> ((x : a) -> f x = g x) -> f = g
extensionality f g = believe_me

leftIdPoint : (f : a -> b) -> (x : a) -> idF (f x) = f x
leftIdPoint f x = Refl

leftId : (f : a -> b) -> (idF . f = f)
leftId f = extensionality (idF . f) f (leftIdPoint f)
```

# Expected Behavior
```
Successfully reloaded
```

# Observed Behavior
```
....:While processing right hand side of leftId at ....
idF is not accessible in this context at:
16      leftId f = extensionality (idF . f) f (leftIdPoint f)
                                   ^^^
```
Asking for the type of the RHS of `leftId` I get:
```
0 b : Type
0 idF : b -> b
0 a : Type
   f : a -> b
```

**Comment by ziman** [comment]
The direct cause of the error message is that `idF` is bound as erased in `leftId` because it's a free implicit but `extensionality` requires an unrestricted quantity of `f`.

There are several ways (and probably others) you could go about this:

1. bind `idF` explicitly as unrestricted
2. make `extensionality` take zero `f`s
3. put `leftId` (or all these functions) entirely at zero quantity by saying `0 leftId : ...`, which effectively makes quantities irrelevant

I suspect that for proofs, the most useful approach is to put them all in `0` and stop worrying about quantities. Otherwise you have to look at where you want computation to happen and plan out what the quantities should be.

When I try the above suggestions, though, I get an error saying "Can't solve constraint between `f x` and `idF (f x)`", which certainly looks strange to me and I can't figure it out but at least it's a non-quantity error...

By the way, `believe_me : a -> b` is a coercion function rather than a postulate, so what you say above is "any proof of `(x : a) -> f x = g x` is a proof of `f = g`". This is a bit strange because one is a function and the other is not so their runtime representations are not interchangeable and you'd get undefined behaviour if you ever evaluate this at runtime. I believe that `believe_me` is the wrong tool for this job but unfortunately, we don't have postulates yet so I'd probably write `extensionality f g h = believe_me $ Refl {x=f}`, which coerces a proof of `f = f` into a proof of `f = g`. I'm not sure how useful this is because you'll probably never run these proofs but I at least wanted to mention it. :)

**Comment by gallais** [comment]
> There are several ways (and probably others) you could go about this:

In this context `idF` should really be the identity function bound above
rather than a variable implicitly quantified over. So I would advise to:

* write `Module.idF` where `Module` is the name of the module currently being defined

**Comment by andorp** [comment]
@ziman: Thanks for the `believe_me` explanation.

**Comment by andorp** [comment]
> write Module.idF where Module is the name of the module currently being defined

```
idF : a -> a
idF = id

extensionality : (f : a -> b) -> (g : a -> b) -> ((x : a) -> f x = g x) -> f = g
extensionality f g = believe_me

leftIdPoint : (f : a -> b) -> (x : a) -> idF (f x) = f x
leftIdPoint f x = Refl

leftId : (f : a -> b) -> (idF . f = f)
leftId f = extensionality (idF . f) f (leftIdPoint f)
```

Which leads to the Can't solve constraints error.

```
Can't solve constraint between:
        f x
and
        idF (f x)
at:
25      leftId f = extensionality (Category.SET.idF . f) f (leftIdPoint f)
26
```

**Comment by andorp** [comment]
I am a bit surprised that there is a different name resolution is needed in the type definition and function definition.

**Comment by andorp** [comment]
But the following snippet works:

```
leftIdPoint : (f : a -> b) -> (x : a) -> Prelude.id (f x) = f x
leftIdPoint f x = Refl

leftId : (f : a -> b) -> (Prelude.id . f = f)
leftId f = extensionality (Prelude.id . f) f (leftIdPoint f)
```

**Comment by andorp** [comment]
As a software developer I would expect that imported public names would be resolved, (and not considered as free variables in terms?) So I had a 'what a surprise' moment. Is this something meant to be this way? As in the example above with `Prelude.id` or it will be changed in future releases?

**Comment by gallais** [comment]
I think the next problem is that you need to `public export` the definition
`idF` for it to reduce at the type level. Once this is done, the unification
algorithm should be able to evaluate `idF (f x)` and see that it is indeed
equal to `f x`.

**Comment by gallais** [comment]
I'll close this and let #621 track the changes.
