### ISSUE TITLE
Local definitions in irrelevant definitions are incorrectly checked for relevance

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#55]
<a href="https://github.com/ohad"><img src="https://avatars3.githubusercontent.com/u/536511?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohad](https://github.com/ohad)**
_Tuesday Apr 21, 2020 at 09:37 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/302_

----

I thought we discussed/reported this at some point, but I can't find the report/fix.

# Steps to Reproduce
```idris
$ cat Irrel.idr 
0
foo : (0 b : Bool) -> Bool
foo b = b

0
bar : Bool
bar = q
  where
    q : Bool
    q = foo True

0
baz : Bool
baz = let q : Bool
          q = foo True in
      q

$ idris2 -c Irrel.idr 
```

# Expected Behavior
```
1/1: Building Irrel (Irrel.idr)
```

# Observed Behavior
```
1/1: Building Irrel (Irrel.idr)
Irrel.idr:10:9--12:1:While processing right hand side of bar at Irrel.idr:7:1--12:1:
While processing right hand side of bar,q at Irrel.idr:10:5--12:1:
Main.foo is not accessible in this context
Irrel.idr:15:15--15:24:While processing right hand side of bar at Irrel.idr:14:1--19:1:
While processing right hand side of bar,q at Irrel.idr:15:11--15:24:
Main.foo is not accessible in this context
```

**Comment by edwinb** [comment]
<a href="https://github.com/edwinb"><img src="https://avatars1.githubusercontent.com/u/255926?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edwinb](https://github.com/edwinb)**
_Tuesday Apr 21, 2020 at 11:12 GMT_

----

Hmm, it's probably just not propagating the multiplicity to the local definition properly. You probably at least noticed that you can work around this for now with an explicit annotation on `q`. (Also that your last `bar` should be `baz` :))

**Comment by edwinb** [comment]
<a href="https://github.com/ziman"><img src="https://avatars1.githubusercontent.com/u/316753?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ziman](https://github.com/ziman)**
_Tuesday Apr 21, 2020 at 11:30 GMT_

----

Assuming that `let (omega q : Bool) = foo True in q` should be equivalent to `(\omega q : Bool => q) (foo True)`, this should typecheck because the result of the lambda is used zero times.

So I don't think the annotation on `q` is inferred wrong. I think that the type checker should accept an `omega` there; is that right?

**Comment by edwinb** [comment]
<a href="https://github.com/ohad"><img src="https://avatars3.githubusercontent.com/u/536511?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ohad](https://github.com/ohad)**
_Tuesday Apr 21, 2020 at 11:44 GMT_

----

@ziman : This is a local definition, and not a let-binding. See the [README](https://github.com/edwinb/Idris2/blob/master/README.md)

**Comment by edwinb** [comment]
<a href="https://github.com/ziman"><img src="https://avatars1.githubusercontent.com/u/316753?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ziman](https://github.com/ziman)**
_Tuesday Apr 21, 2020 at 11:55 GMT_

----

Oh, I see, thanks!

**Comment by gallais** [comment]
IIRC `where` are turned into local `let`-style definitions so we
should be able to solve all of these issues by just looking at the
local let definitions.

I'm marking this as a good first issue because I assume it's just
a matter of digging up where the local definitions are checked and
to combine the parent function's quantity with the `where`-defined
function's.

HOWEVER. This sleuthing could take quite a bit of time. Or turned
out to be more complex than I expect. So be warned.

**Comment by fabianhjr** [comment]
Going to take a stab at this

**Comment by fabianhjr** [comment]
Investigating by the powerful prints:

```
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Main.foo Rig0 > Rig0
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Main.bar Rig0 > Rig0
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Main.foo Rig0 > Rig1
LOG 0: I am not rigSafe
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Main.baz Rig0 > Rig0
LOG 0: I am in getNameType.Nothing: Prelude.Basics.Bool RigW > Rig0
LOG 0: I am in getNameType.Nothing: Main.foo Rig0 > Rig1
LOG 0: I am not rigSafe
```

This comes from: https://github.com/idris-lang/Idris2/blob/50d75cc3a49d47e78bc1e0c08ae45ddf1d98ea34/src/TTImp/Elab/App.idr#L73 and its local `rigSafe` definition. Will research where the local val is being assigned Rig1 since it should be Rig0 from the context.

**Comment by fabianhjr** [comment]
Hey @gallais, I became slightly stuck on researching this; could you give me a bit of context on where are the local variable claims instantiated? Work in progress on #1444

If you change `mult` to `erase` in https://github.com/idris-lang/Idris2/blob/8a81b9649f9c356a6fcc585092c9ad9f8250fe17/src/TTImp/ProcessDef.idr#L860

then the new `linear014` passes however I would like to add linearity context there and I am a bit stuck due to get/set Ctxt magic.

`LOG declare.def.clause:5: Checking RHS (%local ([[] (%claim q Bool), (%def q [q = (foo True)])]) q)`

**Comment by fabianhjr** [comment]
Mhhh, ok so the `ILocal` gets instantiated by `TTImp.Parser` so I will need to research how to propagade from the outer IDef to the inner ILocal [(IClaim)]

**Comment by gallais** [comment]
You've got the right idea:

* See in the parser a local definition is a `PLocal`
* See in the desugarer it becomes an `ILocal`
* See in the elaborator that `checkTerm` (with a given `rig`) elaborates `ILocal` using `checkLocal`


Once you've arrived in `TTImp.Elab.Local` you can notice how we `map setPublic nestdecls_in`
to modify the visibility of the local definition based on its parent's. We probably need to
do something similar in case the parent's `rig` is 0!

**Comment by fabianhjr** [comment]
Hi @gallais, thanks a lot for the context, I was able to get the new test passing without breaking the testsuite.

Though, be warned: 
![image](https://user-images.githubusercontent.com/303897/119155816-2d2ffb00-ba19-11eb-86f2-11a7620cc5aa.png)

**Comment by gallais** [comment]
Not sure what the point of the `InExpr` modification is.
It seems orthogonal to the `localHelper` ones?

**Comment by fabianhjr** [comment]
Hi @gallais, sorry missed some changes, overall it was to get rid of the use of InType mode to check InExpr of Rig0.
