### ISSUE TITLE
unpack is very slow for large strings

### ISSUE THREAD

**Issue by raders** [idris-lang/Idris2#591]
# Steps to Reproduce
```
module test

import Data.Stream

foo : String
foo = pack $ take 100 (repeat 'a')

bar : List Char
bar = unpack foo
```

# Expected Behavior
Evaluating 'bar' should be quick (less than a second) for a 100 character string. Evaluating foo is nearly instantaneous.

# Observed Behavior
On a 2019 MacBook Pro evaluating 'bar' takes about 41s.

**Comment by ziman** [comment]
The [current implementation of `unpack`](https://github.com/idris-lang/Idris2/blob/master/libs/prelude/Prelude/Types.idr#L464) is index-based random-access traversal of `Char`s in the string. This looks quite unsatisfactory but I thought it was written that way because Scheme strings were UTF-32 so they allowed fast random access.

Either way, for other backends (that represent strings in UTF-8), we will need other approaches. Either a [`fastUnpack` function](https://github.com/ziman/idris2/blob/malfunction/libs/prelude/Prelude/Types.idr#L451) implemented using `%foreign` and/or a [string iterator](https://github.com/ziman/idris2/blob/malfunction/libs/contrib/Data/String/Iterator.idr) that lets you iterate over characters in a string in a encoding-independent way. (I had to use `StringIterator` in idris2's lexer when compiling it using my Malfunction backend because otherwise it was horribly slow.)

**Comment by ziman** [comment]
If I say `:exec printLn bar`, it runs fast. Perhaps the REPL evaluator has `O(n)` random char access?

**Comment by raders** [comment]
Yes, it does appear to be an issue with the REPL evaluator. `:exec printLn bar` runs quickly for me as well.

**Comment by gallais** [comment]
This is instantaneous nowadays.
