### ISSUE TITLE
Functions which pattern match on types do not reduce when the parameter is a "built-in" type

### ISSUE THREAD

**Issue by lorenzo-lipparini** [idris-lang/Idris2#650]
# Steps to Reproduce

```idris
isNat : Type -> Bool
isNat Nat = True
isNat _ = False

trivialEquality : isNat Int = False
trivialEquality = Refl
```

# Expected Behavior
`isNat Int` should reduce to `False`, and the program should type-check.

# Observed Behavior
```
Can't solve constraint between:
        False
and
        isNat Int
at:
6       trivialEquality = Refl
```

# Further details

It seems that `isNat t` will not reduce if `t` is a "built-in type"; this has been tested for `Int`,  `Char`, `String`, and `Type` itself.
Conversely, `isNat t` will reduce if `t` is an inductive type; this has been tested for `Void`, `Unit`, `Bool` and `List Int` (apparently, the fact that `List Int` "contains" a built-in type does not cause any issues).

Interestingly, the problem can be fixed by adding a redundant case to the `isNat` function which covers specifically the built-in type:
```idris
isNat : Type -> Bool
isNat Int = False -- with explicit case: the program type-checks
isNat Nat = True
isNat _ = False

trivialEquality : isNat Int = False
trivialEquality = Refl
```

However, the case for the built-in type must precede all the other cases:
```idris
isNat : Type -> Bool
isNat Nat = True
isNat Int = False -- with an explicit case which is not the first: the program is rejected
isNat _ = False

trivialEquality : isNat Int = False
trivialEquality = Refl
```

**Comment by gallais** [comment]
Found the culprit:

https://github.com/idris-lang/Idris2/blob/9565f6cf8b6da9dc0d686c6f0cb804275ec4906a/src/Core/Normalise.idr#L293

`Prelude.Types.Nat` is an `NS _ (UN "Nat")` so we don't even attempt to take this branch
and end up in the catchall at the end that returns a `GotStuck` instead of the `NoMatch`
we could have hoped for.

The solution is to be lazier in the match: take the branch no matter what the name looks
like and *then* make sure it's of the form `UN (show c)`.
