### ISSUE TITLE
Another bug while matching on types

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#705]
# Steps to Reproduce
```idris
bad : (a : Type) -> (x : a) -> String
bad String "good" = "good"
bad _ _ = "bad"
```

# Expected Behavior

`bad String "bad"` reduces to `"bad"`

# Observed Behavior

`bad String "bad"` reduces to `"good"`

**Comment by gallais** [comment]
Using `%logging compile.casetree 10`, it seems that Idris things `"good"` is a forced argument
which leads it to generating the following case tree:

```idris
Runtime tree for Main.bad:
  case {arg:0} : Type of
    String => "good"
    _ => "bad"
```

**Comment by gallais** [comment]
So I think that the problem is that we do normalise primitives functions applied to
primitive values during elaboration via `normalisePrims` in `TTImp.Elab.App`. However
in this one case the fact that `?a = String` has not arrived yet so we have a stuck
term that we never revisit after learning what `?a` is.

**Comment by gallais** [comment]
I have a fix. I'll clean up & push after cycling.
