### ISSUE TITLE
"Rewriting by (prf) did not change type (expr)" -- but it did

### ISSUE THREAD

**Issue by Mr-Andersen** [idris-lang/Idris2#776]
# Steps to Reproduce
```idris
andb_true_elim2_lemma : (a : Bool) -> (a && False = False)
andb_true_elim2_lemma True = Refl
andb_true_elim2_lemma False = Refl

andb_true_elim2 : (b, c : Bool) -> (b && c = True) -> c = True
andb_true_elim2 b False p = rewrite andb_true_elim2_lemma b in p
andb_true_elim2 b True p = Refl
```
Then typecheck it with `idris2 exercise.idr`

# Expected Behavior
Typechecks successfully.

# Observed Behavior
```
1/1: Building exercise (exercise.idr)
Error: While processing right hand side of andb_true_elim2. Rewriting by b && Delay False = False did not change type False = True.

exercise.idr:6:29--6:65
   |
 6 | andb_true_elim2 b False p = rewrite andb_true_elim2_lemma b in p
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is this a bug? Before rewriting `p : b && Delay False = True`, rewriting it with `andb_true_elim2_lemma b : b && Delay False = False` should transform it into `False = True`.

**Comment by buzden** [comment]
With the `rewrite ... in` construction you always rewrite the *result* type of expression.

If you will write your first clause with a hole (i.e. as ``andb_true_elim2 b False p = ?x``) you'll see that the type of `x` is `False = True`. Rewriting rule rewrites this particular type, i.e. `False = True` in this case. Thus, rewriting rule must be of type `True = ...` or `False = ...` because the type to be rewritten contains only `False` and `True` as subexpressions.

For example, consider two (intentionally unimplemented) functions:

```
whatever : Nat -> Bool

whatever_rule : True = whatever 0
```

If you write your first case like this:

```
andb_true_elim2 : (b, c : Bool) -> (b && c = True) -> c = True
andb_true_elim2 b False p = rewrite whatever_rule in ?x
andb_true_elim2 b True p = Refl
```

you'll see that the type of `x` (i.e. the resulting type) has been rewritten from `False = True` to `False = whatever 0`, i.e. definitely according to the rewriting rule `True = whatever 0` (disregarding to what the `whatever` function does).

However, in your case your rewriting rule `andb_true_elim2_lemma b` has type `b && False = False`. You can see that the left side of this equation is not in the type of `False = True` type of the case `andb_true_elim2 b False p`.

So, this is not a bug.

**Comment by Mr-Andersen** [comment]
You could say that I just need
```idris
andb_true_elim2_lemma : (a : Bool) -> (False = a && False)
```
Understandable, thank you for explanation

**Comment by clayrat** [comment]
> You could say that I just need
> 
> ```idris
> andb_true_elim2_lemma : (a : Bool) -> (False = a && False)
> ```

This actually already exists in stdlib: https://github.com/idris-lang/Idris2/blob/master/libs/base/Data/Bool.idr#L18

**Comment by Mr-Andersen** [comment]
@clayrat Thx, I was solving problems from Software Foundations, so I re-implemented these things by hand
