### ISSUE TITLE
Totality Checker fails with false positives

### ISSUE THREAD

**Issue by mattpolzin** [idris-lang/Idris2#794]
The totality checker seems to get dangerously confused around a lot of code related to (List) views. I hit limitations and false positives in a few places when experimenting with the views suggested by Type Driven Development with Idris.

For example, here's `SnocList` (actually borrowed from the `base` library to be sure I was not doing something wrong in translating the book's Idris 1 into valid Indris 2).
```idris
||| View for traversing a list backwards
public export
data SnocList : List a -> Type where
     Empty : SnocList []
     Snoc : (x : a) -> (xs : List a) ->
            (rec : SnocList xs) -> SnocList (xs ++ [x])
```

And here's a function that trips up both case splitting and totality checking:
```idris
tmp : {xs : List a} -> SnocList (x :: xs) -> a
tmp Empty impossible
```
Case splitting on its only argument automatically produces the result seen above and when you ask Idris 2 whether `tmp` is total, it says yes.

It's worth noting that you get a different result if you attempt to pass in what is ostensibly a more reasonable type given that it matches the signature of the  second constructor for `SnocList`. You get "No valid case splits" in this case:
```idris
tmp : {xs : List a} -> SnocList (xs ++ [x]) -> a
tmp y = ?tmp_rhs
```

That's clearly a silly example, but I also found that the same limitations made it impossible for me to create a `Decidable` version of the `palindrome` function (one of the book's exercise problems) -- that made me pretty sad because it was exciting to see things come together until I reached the point where I could not prove that `Palindrome xs -> Void` implies `Palindrome (x :: (xs ++ [x])) -> Void`.

This only appears to happen (in the examples I have found so far) when list appending (as above) is involved. Interestingly, `with` does seem to work correctly, it is just top-level case splitting and totality checking that fails for these data types.

```idris
tmp2 : List a -> a
tmp2 xs with (snocList xs)
  tmp2 [] | Empty = ?tmp_rhs_1
  tmp2 (xs ++ [x]) | (Snoc rec) = ?tmp_rhs_2
```
I know, I can't finish that function in any reasonable way for an empty list, but the point is that the `with` was able to pattern match in the way I would have wanted to see my first function above be able to.

**Comment by mattpolzin** [comment]
I've figured a few things about this issue out. 

First, it's not that `with` is working differently but rather that `with (snocList xs)` is the simpler case of matching arbitrary `xs` rather than matching `xs ++ [x]` or even just the non-empty list `x :: xs`. 

Second, I've worked around this limitation in the case of the Decidable Palindrome example by providing proof based on `Palindrome xs`, `Palindrome ys`, and proof that `ys = x :: (xs ++ [x])`. It's a bit clunkier to work with but it does work. 

Which leaves me with this conclusion still for this issue: the case splitting and totality behavior seen in my first example (`tmp`) is a bug of some kind and would be better off as an error or "No cases found" than its current state which allows proving of arbitrary untrue things.

**Comment by gallais** [comment]
Given you looked into it yourself and may be interested in the details, here's how
my thinking went:

> ```idris
> tmp : {xs : List a} -> SnocList (x :: xs) -> a
> tmp Empty impossible
> ```

According to logging, this does spark an impossibility check for `tmp (Snoc _ _ _)`.
If you try to write:

```idris
tmp : {xs : List a} -> SnocList (x :: xs) -> a
tmp (Snoc _ _ _) impossible
```

then Idris rightfully complains that this case is not in fact impossible. So the problem
is that the check sparked by the coverage checker must have been slightly different from
the one sparked by the user-written `impossible`.

The impossibility check is pretty conservative and in case it finds an error, it tries
to analyse it to make sure it is not possible to recover from it. Indeed there are scenario
in which errors can go away:

* if the problem was under-constrained, instantiating a couple of metas could do the trick
* if some expression got stuck during evaluation, having slightly more concrete terms could
  make things work

In these cases, it is unsafe to assume the match is impossible. The second case is the scenario
that makes the `(x :: xs) ~ (ys ++ [y])` error sparked by `tmp (Snoc _ _ _)` recoverable:
if you somehow figured out that `ys ~ []` then you could happily solve `x ~ y` and `xs ~ []`!



SO. Something goes wrong in the code checking whether a unification error between two values
can be recovered from. The check ends with a catch-all:

```idris
-- OTHERWISE: no
recoverable defs x y = pure False
```

so we probably screwed up earlier. And indeed: the check is not symmetric! We have some
short-circuiting cases that fire if the `x` has a certain shape but we don't have the
same logic for `y`!

It's an easy fix once you got there. PR incoming. :)

**Comment by mattpolzin** [comment]
@gallais thanks for explaining the fix! I did very much enjoy reading about it.
