### ISSUE TITLE
JavaScript Backend: can't construct a string for %foreign pragma through a function call

### ISSUE THREAD

**Issue by DoctorRyner** [idris-lang/Idris2#800]
# Steps to Reproduce

1. Download this repo https://github.com/DoctorRyner/idris-js/tree/aa01a92ad994e21563a3be98ca4ca4ea78d7625f
2. Open the repo and try to build it `idris2 --build js.ipkg`
3. Get this error:
```
src/Js/Console.idr:5:11--5:40:%foreign calling convention must evaluate to a String at:
5       %foreign (js "(_, x) => console.log(x)")
```

# Expected Behavior

Being able to use the function `js` from `Js.FFI` module. If `js` function declared in the `Js.Console` module, it works fine

# Observed Behavior

I'm unable to use `js` function if it's imported from the `Js.FFI` module

**Comment by gallais** [comment]
Did you forget to commit `Js.FFI`?

**Comment by DoctorRyner** [comment]
Ah, it seems so.

Js.FFI should be:

```idris
module Js.FFI

export
js : String -> String
js = ("javascript:lambda:" ++)
```

**Comment by gallais** [comment]
Have you tried declaring `js` to be `total` so that it may reduce?

**Comment by DoctorRyner** [comment]
Wow `public export` seems to fix this, how does it work?

**Comment by gallais** [comment]
`export` only makes the declaration available to the outside world.
`public` also exposes the definition.

This means that when you `public export` a function, the evaluator
is able to unfold it instead of getting stuck. Here it's enough for
the whole thing to evaluate to a `String` literal which is what
`%foreign` wants.
