### ISSUE TITLE
Improve error message with missing part of interface

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#868]
`Idris 2, version 0.2.1-60e9cf44b`

# Steps to Reproduce

```idris
module Bug

data Identity a = MkIdentity a

Functor Identity where
    map f (MkIdentity v) = MkIdentity (f v)

Foldable Identity where
    foldr f a (MkIdentity v) = f v a

Traversable Identity where
    traverse f (MkIdentity v) = MkIdentity <$> f v

main : IO ()
main = do
    let x = sequence (MkIdentity (Just ()))
    pure ()
```

`idris2 Bug.idr -o bug`

# Expected Behavior

~~Compiles without errors~~
~~Have default implementation of null so it compiles without errors~~

Have an error message that clearly specifies that `null` is missing in the implementation of `Foldable Identity`.

# Observed Behavior

`Warning: compiling hole Bug.null`

Replacing `sequence` with `traverse id` makes the error go away.

**Comment by gallais** [comment]
`Foldable` has a `null` method. You have not provided it hence the leftover hole.

**Comment by michaelmesser** [comment]
@gallais Thank you. I guess that makes sense. I didn't realize that `null` was added. I still have a couple of questions:

- Why is the behavior different for `sequence` and `traverse id`?
- Would is be possible to improve the error message to something like `null` is missing in implementation of `Foldable Identity`?
- Would it be possible to add a default definition of `null`? https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.Foldable.html#null

**Comment by gallais** [comment]
> Why is the behavior different for `sequence` and `traverse id`?

I am not sure. It could be that the definition of `traverse` gets
specialised and inlined in one case but the indirection introduced
by `sequence` in the other means we end up needing to build the
dictionary and thus find out about the missing field?

> Would is be possible to improve the error message to something like
  `null` is missing in implementation of `Foldable` Identity?

I guess so. We could add some contextual information.

> Would it be possible to add a default definition of `null`?

Because Idris is not lazy, it's probably a bad idea to write it this way:
`foldr c n (x :: xs) = c n (foldr c n xs)` means that the recursive call
will be fully evaluated before `c` is called. This means that `null` defined
this way is linear in the size of the `t a` input.

**Comment by michaelmesser** [comment]
I wonder if there is a single function that `null` and `foldr` could be efficiently implemented in terms of. Perhaps by using lazy or some explicit way to return early.

**Comment by gallais** [comment]
Actually it may be possible to get an efficient default
implementation by specifying the accumulator should be lazy
like so:

```idris
null = foldr {acc = Lazy Bool} (\ _,_ => False) True
```

ping @alissa42

**Comment by michaelmesser** [comment]
@gallais  I test that with `unsafePerformIO` to see how many times the function is called and I believe it works correctly.
